- Macro HS : 50-20
- Firm HS : 20-20

## **설정**

In [ ]:
## Google Drive Amount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
## Import libaries
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
## Setting
base_path = '/content/drive/MyDrive/CS/'

## **데이터 불러오기**

### **Firm**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'hidden_states', 'CNNLSTM_Firm_simple')

train_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_20_20_Firm.csv'))

In [ ]:
train_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,ERTS,16721,75828,7372,3.0,11.0,36,1997,0.064718,1997-01-31,...,0.028291,-0.007866,0.023190,-0.168285,-0.121665,-0.038322,-0.084682,-0.117417,-0.006333,0.107252
1,BMCS,14650,11976,7372,3.0,11.0,36,1997,0.048338,1997-01-31,...,0.032954,-0.016959,0.025945,-0.175594,-0.120998,-0.043793,-0.091056,-0.118346,-0.005521,0.112488
2,LOW,6829,61399,5211,1.0,11.0,43,1997,-0.068632,1997-01-31,...,0.035294,-0.014530,0.025004,-0.173039,-0.132915,-0.045645,-0.091474,-0.115696,-0.006687,0.123626
3,NKE,7906,57665,3021,1.0,11.0,10,1997,0.139583,1997-01-31,...,0.022729,-0.023995,0.030466,-0.171475,-0.120554,-0.037044,-0.110117,-0.132952,-0.001920,0.108977
4,CPC,61404,82295,7500,1.0,11.0,33,1997,0.014925,1997-01-31,...,0.027012,-0.034333,0.026528,-0.172744,-0.121261,-0.049424,-0.100359,-0.121147,0.000458,0.118068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200964,NOC,7985,24766,3812,1.0,11.0,37,2014,0.045838,2014-12-31,...,0.028322,-0.020363,0.029617,-0.184254,-0.114508,-0.045516,-0.087337,-0.126549,-0.008538,0.113358
200965,CVX,2991,14541,2911,1.0,11.0,30,2014,0.030403,2014-12-31,...,-0.004557,-0.031406,0.020202,-0.165850,-0.117160,-0.033731,-0.110053,-0.128346,0.000837,0.108359
200966,NOV,63892,84032,3533,1.0,11.0,21,2014,-0.015662,2014-12-31,...,0.024741,-0.028163,0.029501,-0.187490,-0.113842,-0.049172,-0.094033,-0.127666,-0.006647,0.111515
200967,APO,184254,12591,6282,1.0,11.0,48,2014,-0.035188,2014-12-31,...,0.027518,-0.034797,0.027056,-0.172068,-0.124870,-0.042095,-0.095095,-0.112806,-0.001466,0.122732
200968,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,0.037704,-0.021195,0.020401,-0.178642,-0.124031,-0.047027,-0.089720,-0.111678,-0.008424,0.117021

In [ ]:
valid_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2015,-0.074988,2015-01-31,...,0.026567,-0.016915,0.025953,-0.171181,-0.112156,-0.039687,-0.104199,-0.127550,-0.007495,0.102085
1,LEN,6669,52708,1531,1.0,11.0,18,2015,0.003124,2015-01-31,...,0.016007,-0.024501,0.023155,-0.180788,-0.113822,-0.043913,-0.100784,-0.135893,-0.005865,0.109427
2,LH,14960,12062,8071,1.0,11.0,11,2015,0.063763,2015-01-31,...,0.035078,-0.022535,0.028517,-0.177842,-0.115206,-0.046598,-0.095281,-0.115647,-0.010728,0.109484
3,LII,122380,87034,3585,1.0,11.0,21,2015,0.034080,2015-01-31,...,0.034646,-0.019149,0.022177,-0.180713,-0.123819,-0.049908,-0.087230,-0.116596,-0.008228,0.117506
4,ATR,28176,79133,3089,1.0,11.0,15,2015,-0.051616,2015-01-31,...,0.035715,-0.022084,0.025698,-0.179924,-0.121552,-0.048855,-0.089112,-0.117722,-0.007429,0.116795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34686,NEU,4462,42550,2860,1.0,11.0,14,2017,-0.003445,2017-12-31,...,0.034292,-0.018306,0.023190,-0.178181,-0.124788,-0.044017,-0.091220,-0.116545,-0.007320,0.117605
34687,NEM,7881,21207,1040,1.0,11.0,27,2017,0.016356,2017-12-31,...,0.028763,-0.021891,0.021246,-0.181541,-0.114759,-0.044341,-0.097377,-0.129094,-0.005299,0.109074
34688,NEE,4517,24205,4911,1.0,11.0,31,2017,-0.011706,2017-12-31,...,0.019930,-0.027107,0.025571,-0.179420,-0.121367,-0.043505,-0.097075,-0.123316,-0.006829,0.116957
34689,NOC,7985,24766,3812,1.0,11.0,37,2017,0.001659,2017-12-31,...,0.029602,-0.019504,0.028004,-0.180424,-0.119011,-0.047249,-0.093908,-0.119810,-0.011278,0.110710
34690,ZTS,13721,13788,2834,1.0,11.0,13,2017,-0.003458,2017-12-31,...,0.035575,-0.011329,0.023760,-0.180566,-0.124087,-0.042748,-0.082984,-0.116031,-0.009348,0.114566

In [ ]:
test_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2018,0.096461,2018-01-31,...,0.035436,-0.015706,0.028321,-0.176203,-0.114643,-0.045251,-0.098269,-0.114701,-0.012483,0.104588
1,LLL,110685,86021,3812,1.0,11.0,37,2018,0.073844,2018-01-31,...,0.031223,-0.022190,0.029893,-0.181655,-0.118415,-0.046082,-0.089001,-0.120674,-0.008757,0.115599
2,LLY,6730,50876,2834,1.0,11.0,13,2018,-0.035638,2018-01-31,...,0.027470,-0.013187,0.023839,-0.178150,-0.124271,-0.041893,-0.093218,-0.121877,-0.010802,0.112201
3,LM,6653,65330,6282,1.0,11.0,48,2018,0.015245,2018-01-31,...,0.040769,-0.020485,0.030661,-0.176477,-0.113864,-0.046428,-0.091919,-0.119390,-0.007562,0.110765
4,LMT,6774,21178,3760,1.0,11.0,26,2018,0.105280,2018-01-31,...,0.014493,-0.012252,0.025593,-0.172696,-0.124126,-0.033631,-0.101393,-0.129580,-0.011280,0.108928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11560,AKAM,125595,87299,7370,3.0,11.0,36,2018,-0.111564,2018-12-31,...,0.041080,-0.018627,0.022229,-0.177067,-0.121872,-0.050269,-0.094039,-0.105799,-0.011501,0.113171
11561,SLM,20430,66325,6141,3.0,11.0,45,2018,-0.190847,2018-12-31,...,0.031181,-0.029544,0.024388,-0.179225,-0.127731,-0.045825,-0.089269,-0.113244,-0.004208,0.123345
11562,FCX,14590,81774,1000,1.0,11.0,28,2018,-0.136516,2018-12-31,...,0.030963,-0.024622,0.018736,-0.177877,-0.128327,-0.045771,-0.094385,-0.114665,-0.007811,0.125633
11563,SNAP,30091,16595,7370,1.0,11.0,36,2018,-0.153610,2018-12-31,...,0.017286,-0.012426,0.017683,-0.163788,-0.107012,-0.030614,-0.083088,-0.121814,-0.018666,0.086257
11564,ZTS,13721,13788,2834,1.0,11.0,13,2018,-0.088740,2018-12-31,...,0.037183,-0.016096,0.023275,-0.179821,-0.123490,-0.048574,-0.093133,-0.112396,-0.012563,0.113149

### **Macro**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'hidden_states', 'CNN_BiLSTM_macro')

train_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_50_20_macro.csv'))

train_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_50_20_macro.csv'))

train_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_50_20_macro.csv'))

train_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_50_20_macro.csv'))

In [ ]:
train_macro_2018

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,1997-01-01,0.070149,0.026641,-0.084782,0.022162,-0.014845,-0.147834,0.063682,0.074618,0.039699,...,0.107266,0.081205,0.002767,-0.029662,-0.100859,-0.035114,0.100308,0.096447,0.032497,-0.025069
1,1997-02-01,0.070096,0.028521,-0.080924,0.023861,-0.011429,-0.144107,0.062332,0.072179,0.039941,...,0.105271,0.081750,0.003310,-0.028290,-0.101918,-0.033484,0.098883,0.097605,0.031811,-0.023289
2,1997-03-01,0.074675,0.032451,-0.081469,0.024248,-0.009215,-0.140306,0.063603,0.072668,0.044113,...,0.105183,0.079334,0.004421,-0.022812,-0.098573,-0.032283,0.095027,0.101236,0.037928,-0.025956
3,1997-04-01,0.074176,0.029853,-0.083413,0.024465,-0.006169,-0.140812,0.065021,0.072021,0.044765,...,0.105460,0.076547,0.005783,-0.021139,-0.097457,-0.030115,0.096540,0.101212,0.038515,-0.026322
4,1997-05-01,0.075383,0.025085,-0.090750,0.024673,-0.001685,-0.143357,0.066440,0.074132,0.045670,...,0.105526,0.074704,0.010062,-0.024030,-0.102989,-0.034086,0.095300,0.101363,0.039429,-0.027126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2014-08-01,0.092203,0.014796,-0.065993,-0.006009,-0.004482,-0.119058,0.058297,0.079264,0.045877,...,0.121196,0.087666,0.014589,-0.037410,-0.096965,-0.052499,0.081737,0.098911,0.031273,0.005789
212,2014-09-01,0.094048,0.013823,-0.062257,-0.005608,-0.010076,-0.120749,0.050690,0.082587,0.049286,...,0.120179,0.088277,0.015115,-0.034019,-0.096837,-0.051169,0.082248,0.098569,0.029388,0.005349
213,2014-10-01,0.088064,0.012511,-0.057809,-0.002092,-0.008500,-0.118926,0.052133,0.079987,0.047129,...,0.123001,0.093767,0.014144,-0.035067,-0.099852,-0.051980,0.081985,0.101247,0.030015,0.002896
214,2014-11-01,0.092617,0.011348,-0.052634,-0.000958,-0.010778,-0.116099,0.052263,0.079566,0.040323,...,0.122579,0.093177,0.011663,-0.039779,-0.099824,-0.056204,0.082954,0.099119,0.028078,0.001192
215,2014-12-01,0.088281,0.012987,-0.053589,-0.001348,-0.014115,-0.115602,0.050271,0.084040,0.041860,...,0.122927,0.095342,0.016558,-0.036471,-0.099846,-0.049030,0.084147,0.097920,0.025161,0.003549

In [ ]:
valid_macro_2018

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,2015-01-01,0.090227,0.013915,-0.054108,-0.002592,-0.013973,-0.116778,0.058180,0.080989,0.044425,...,0.122110,0.089066,0.017753,-0.036447,-0.096185,-0.046043,0.077678,0.096930,0.028338,0.003858
1,2015-02-01,0.089060,0.012646,-0.056528,-0.001104,-0.015757,-0.119190,0.059186,0.082151,0.044342,...,0.123121,0.087417,0.018197,-0.036110,-0.096284,-0.043305,0.079559,0.094268,0.025081,0.002131
2,2015-03-01,0.088156,0.016061,-0.052153,0.000870,-0.015414,-0.120767,0.058366,0.082766,0.040301,...,0.125487,0.087377,0.015961,-0.032341,-0.097823,-0.047856,0.081247,0.095415,0.024029,0.001928
3,2015-04-01,0.084952,0.016498,-0.046696,-0.001158,-0.022642,-0.121881,0.060018,0.080619,0.038828,...,0.125211,0.087818,0.013170,-0.034921,-0.098073,-0.044035,0.079277,0.094337,0.024512,0.005041
4,2015-05-01,0.083803,0.012806,-0.044659,-0.000520,-0.026863,-0.121408,0.061780,0.082362,0.041459,...,0.123280,0.089322,0.012469,-0.037890,-0.097582,-0.044378,0.076295,0.094054,0.026630,0.004748
5,2015-06-01,0.080303,0.012864,-0.046001,0.001358,-0.025287,-0.119349,0.064534,0.083788,0.044438,...,0.122377,0.087050,0.013756,-0.034263,-0.096925,-0.042444,0.076152,0.094932,0.029933,0.004627
6,2015-07-01,0.077690,0.012572,-0.044133,0.004887,-0.024786,-0.123074,0.063160,0.083453,0.041850,...,0.120865,0.086067,0.011898,-0.033101,-0.102079,-0.040499,0.077692,0.092079,0.028311,0.005709
7,2015-08-01,0.081490,0.014168,-0.043908,0.003647,-0.022267,-0.117153,0.067267,0.080183,0.042842,...,0.118629,0.081432,0.017915,-0.031311,-0.100947,-0.046369,0.076601,0.094447,0.030638,0.001815
8,2015-09-01,0.082067,0.015206,-0.043538,0.003335,-0.021704,-0.117708,0.061129,0.080326,0.037230,...,0.121750,0.081641,0.018432,-0.027713,-0.101517,-0.045451,0.081456,0.096026,0.028471,0.003600
9,2015-10-01,0.083505,0.017005,-0.044250,0.002919,-0.023423,-0.117648,0.063592,0.080361,0.038513,...,0.125389,0.080825,0.013610,-0.031303,-0.095653,-0.040036,0.077255,0.093899,0.026725,0.003458
10,2015-11-01,0.086032,0.018305,-0.047399,-0.004391,-0.026712,-0.118569,0.062889,0.081275,0.039622,...,0.123102,0.077938,0.015362,-0.031984,-0.095229,-0.038677,0.074555,0.096393,0.033233,0.000540
11,2015-12-01,0.081217,0.015260,-0.045328,0.002834,-0.028357,-0.122943,0.065297,0.085002,0.036800,...,0.126126,0.082471,0.010233,-0.036809,-0.097804,-0.036490,0.074482,0.096129,0.025128,0.003213
12,2016-01-01,0.081125,0.013367,-0.044263,0.003810,-0.027569,-0.123391,0.065675,0.082795,0.036564,...,0.125968,0.080573,0.013654,-0.038579,-0.099480,-0.036890,0.077722,0.093978,0.023242,0.004333
13,2016-02-01,0.085914,0.014516,-0.047660,0.008091,-0.025918,-0.124122,0.063681,0.083878,0.037553,...,0.124473,0.077511,0.015237,-0.033965,-0.098077,-0.039314,0.075825,0.096164,0.027963,-0.001316
14,2016-03-01,0.085006,0.011900,-0.044020,0.007443,-0.025470,-0.122433,0.063914,0.085261,0.033572,...,0.124961,0.079319,0.016578,-0.037945,-0.103125,-0.036957,0.076133,0.096410,0.021357,0.000362
15,2016-04-01,0.086973,0.012347,-0.042427,0.008950,-0.028064,-0.124555,0.059816,0.087075,0.033342,...,0.127052,0.079502,0.016347,-0.036806,-0.102732,-0.037393,0.076032,0.097703,0.024933,0.001344
16,2016-05-01,0.084541,0.013052,-0.047861,0.005748,-0.026982,-0.125202,0.061641,0.087627,0.034819,...,0.125131,0.078643,0.014455,-0.033361,-0.098602,-0.032678,0.074932,0.096941,0.026246,-0.001317
17,2016-06-01,0.090106,0.012486,-0.046571,0.005730,-0.029346,-0.124482,0.059586,0.086642,0.035738,...,0.121373,0.079436,0.014525,-0.032493,-0.100328,-0.034116,0.077786,0.093532,0.024235,-0.000187
18,2016-07-01,0.084926,0.011741,-0.042935,0.009936,-0.029829,-0.123074,0.064619,0.087448,0.034877,...,0.121169,0.078897,0.018613,-0.034608,-0.099749,-0.035840,0.076192,0.094714,0.021791,0.000759
19,2016-08-01,0.094105,0.008426,-0.047742,0.008844,-0.030423,-0.123239,0.059524,0.086856,0.037088,...,0.119081,0.079004,0.017487,-0.033329,-0.097398,-0.040580,0.073540,0.096313,0.025782,-0.004641
20,2016-09-01,0.093659,0.008884,-0.050872,0.009331,-0.032477,-0.127326,0.056904,0.089933,0.035961,...,0.118882,0.076780,0.015900,-0.034148,-0.099050,-0.037314,0.072177,0.096455,0.026652,-0.005619
21,2016-10-01,0.091198,0.007635,-0.048258,0.007970,-0.032925,-0.127063,0.058303,0.088145,0.035196,...,0.117678,0.078562,0.016070,-0.034943,-0.100438,-0.033448,0.074366,0.092053,0.023452,-0.002344
22,2016-11-01,0.092456,0.003524,-0.053329,0.011134,-0.036056,-0.131679,0.057123,0.089419,0.035453,...,0.116400,0.076285,0.014506,-0.037498,-0.100054,-0.036399,0.072860,0.093587,0.026190,-0.006686
23,2016-12-01,0.095032,0.002106,-0.053591,0.010805,-0.035191,-0.131785,0.054363,0.088627,0.033539,...,0.116984,0.078983,0.012591,-0.038178,-0.101574,-0.040915,0.075291,0.092650,0.023895,-0.007684
24,2017-01-01,0.091088,0.003083,-0.048877,0.011711,-0.035075,-0.129454,0.054371,0.088637,0.031831,...,0.115037,0.079199,0.017808,-0.035205,-0.103166,-0.038401,0.080638,0.090193,0.022998,-0.004305
25,2017-02-01,0.086749,0.005758,-0.046334,0.012794,-0.038911,-0.130224,0.053180,0.088142,0.034717,...,0.115744,0.079804,0.016053,-0.037930,-0.103907,-0.036722,0.079142,0.089521,0.026828,-0.004230
26,2017-03-01,0.095571,0.004973,-0.050373,0.014572,-0.037881,-0.131410,0.050140,0.089606,0.034060,...,0.116661,0.079662,0.016163,-0.038299,-0.103231,-0.037662,0.076312,0.093191,0.027211,-0.003559
27,2017-04-01,0.092875,0.003647,-0.047824,0.014362,-0.036950,-0.132339,0.052207,0.088033,0.033383,...,0.114863,0.079706,0.017667,-0.037025,-0.104036,-0.038940,0.079786,0.090847,0.027263,-0.004271
28,2017-05-01,0.095787,0.006149,-0.046204,0.016879,-0.035500,-0.130892,0.051170,0.086120,0.034403,...,0.115035,0.078458,0.019503,-0.034570,-0.103968,-0.041118,0.078930,0.090202,0.028578,-0.005261
29,2017-06-01,0.096462,0.006497,-0.043991,0.014918,-0.041030,-0.130642,0.047125,0.087886,0.032951,...,0.115895,0.080057,0.019893,-0.034918,-0.103581,-0.044063,0.078887,0.092944,0.031089,-0.003278
30,2017-07-01,0.096119,0.004439,-0.046728,0.014936,-0.040585,-0.129895,0.050130,0.088611,0.036447,...,0.115597,0.081969,0.021229,-0.035386,-0.102028,-0.047944,0.078959,0.092508,0.031273,-0.007212
31,2017-08-01,0.098423,0.005556,-0.045213,0.011840,-0.041488,-0.133057,0.049490,0.088970,0.032980,...,0.115873,0.078637,0.018571,-0.034953,-0.102079,-0.045078,0.076264,0.091965,0.030659,-0.006463
32,2017-09-01,0.094501,0.006719,-0.044560,0.013366,-0.041707,-0.135389,0.047487,0.089056,0.031185,...,0.116758,0.082182,0.017491,-0.036324,-0.104998,-0.044779,0.076869,0.089873,0.026947,-0.003948
33,2017-10-01,0.095565,0.003773,-0.044825,0.014175,-0.041497,-0.133713,0.047512,0.088050,0.033184,...,0.116063,0.081349,0.016983,-0.036170,-0.103903,-0.047687,0.077554,0.087425,0.025845,-0.006069
34,2017-11-01,0.095768,0.004006,-0.048602,0.014413,-0.045266,-0.137123,0.046088,0.090951,0.030993,...,0.115773,0.080964,0.015879,-0.035492,-0.103574,-0.048605,0.077957,0.091637,0.026972,-0.007069
35,2017-12-01,0.099283,0.003752,-0.047020,0.011396,-0.041439,-0.135442,0.050703,0.087121,0.033252,...,0.116481,0.081275,0.016657,-0.037053,-0.101417,-0.050111,0.074398,0.090395,0.026132,-0.005355

In [ ]:
test_macro_2021

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,2021-01-01,0.046070,0.015667,-0.037206,0.013960,-0.040053,-0.127029,0.067570,0.050489,0.045864,...,0.059283,0.108644,-0.008964,-0.055035,-0.050208,-0.058489,0.080867,0.107515,0.050258,-0.065023
1,2021-02-01,0.053123,0.011049,-0.043294,0.018113,-0.038661,-0.118215,0.071021,0.060474,0.047030,...,0.068086,0.104278,-0.000653,-0.052075,-0.051364,-0.063873,0.077380,0.116496,0.057234,-0.064883
2,2021-03-01,0.043557,0.011968,-0.037646,0.021233,-0.032869,-0.116744,0.074380,0.059587,0.047768,...,0.062505,0.102483,-0.006114,-0.042291,-0.047713,-0.070582,0.081079,0.115008,0.060131,-0.064931
3,2021-04-01,0.047208,0.012500,-0.043793,0.026401,-0.029725,-0.110550,0.069100,0.065938,0.046546,...,0.065876,0.105642,-0.000187,-0.041649,-0.049998,-0.070395,0.076995,0.116036,0.062523,-0.063837
4,2021-05-01,0.043483,0.012423,-0.037881,0.030178,-0.031920,-0.109866,0.071386,0.062217,0.047074,...,0.062199,0.105500,-0.006182,-0.042926,-0.048730,-0.074707,0.075852,0.119099,0.064891,-0.069232
5,2021-06-01,0.041207,0.010702,-0.048689,0.036840,-0.031306,-0.115150,0.071409,0.067588,0.048611,...,0.063059,0.103327,-0.004147,-0.045018,-0.049707,-0.073787,0.072640,0.121641,0.063487,-0.072458
6,2021-07-01,0.037152,0.017642,-0.048765,0.040492,-0.038720,-0.117516,0.066516,0.066717,0.049088,...,0.059202,0.103578,-0.007770,-0.046378,-0.048290,-0.070604,0.069389,0.119302,0.059221,-0.071624
7,2021-08-01,0.031721,0.017481,-0.052439,0.044999,-0.039844,-0.118576,0.062035,0.074140,0.047282,...,0.055833,0.108024,-0.012953,-0.043661,-0.050192,-0.065861,0.069520,0.125073,0.060524,-0.077921
8,2021-09-01,0.032610,0.019418,-0.058163,0.050299,-0.044358,-0.119532,0.066931,0.076094,0.052969,...,0.060974,0.105385,-0.009363,-0.042415,-0.048964,-0.070897,0.069157,0.132095,0.062579,-0.080058
9,2021-10-01,0.039257,0.021841,-0.055765,0.053800,-0.042243,-0.118470,0.066281,0.075751,0.053382,...,0.058574,0.106580,-0.008698,-0.044359,-0.048486,-0.065362,0.065062,0.127409,0.062083,-0.077315
10,2021-11-01,0.035008,0.025427,-0.052783,0.053024,-0.046999,-0.118465,0.066663,0.077917,0.054409,...,0.058462,0.109892,-0.008445,-0.046251,-0.047685,-0.063467,0.064225,0.127543,0.061679,-0.077804
11,2021-12-01,0.031502,0.025931,-0.045330,0.055737,-0.051793,-0.116901,0.071304,0.079890,0.052084,...,0.056402,0.107323,-0.011753,-0.044426,-0.045323,-0.066329,0.064487,0.133025,0.060711,-0.082662

## **병합**

In [ ]:
def generate_year_month_forMacro(train, valid, test):
  ## Datetime 변환
  train['sasdate']=pd.to_datetime(train['sasdate'])
  valid['sasdate']=pd.to_datetime(valid['sasdate'])
  test['sasdate']=pd.to_datetime(test['sasdate'])

  ## Join할 year, month 변수 생성
  train['year'] = train['sasdate'].dt.year
  train['month'] = train['sasdate'].dt.month

  valid['year'] = valid['sasdate'].dt.year
  valid['month'] = valid['sasdate'].dt.month

  test['year'] = test['sasdate'].dt.year
  test['month'] = test['sasdate'].dt.month

  return(train, valid, test)

def generate_year_month_forFirm(train, valid, test):
  ## Datetime 변환
  train['date']=pd.to_datetime(train['date'])
  valid['date']=pd.to_datetime(valid['date'])
  test['date']=pd.to_datetime(test['date'])

  ## Join할 year, month 변수 생성
  train['year'] = train['date'].dt.year
  train['month'] = train['date'].dt.month

  valid['year'] = valid['date'].dt.year
  valid['month'] = valid['date'].dt.month

  test['year'] = test['date'].dt.year
  test['month'] = test['date'].dt.month

  return(train, valid, test)

In [ ]:
train_macro_2018_temp, valid_macro_2018_temp, test_macro_2018_temp = generate_year_month_forMacro(train_macro_2018, valid_macro_2018, test_macro_2018)
train_macro_2019_temp, valid_macro_2019_temp, test_macro_2019_temp = generate_year_month_forMacro(train_macro_2019, valid_macro_2019, test_macro_2019)
train_macro_2020_temp, valid_macro_2020_temp, test_macro_2020_temp = generate_year_month_forMacro(train_macro_2020, valid_macro_2020, test_macro_2020)
train_macro_2021_temp, valid_macro_2021_temp, test_macro_2021_temp = generate_year_month_forMacro(train_macro_2021, valid_macro_2021, test_macro_2021)

train_firm_2018_temp, valid_firm_2018_temp, test_firm_2018_temp = generate_year_month_forFirm(train_firm_2018, valid_firm_2018, test_firm_2018)
train_firm_2019_temp, valid_firm_2019_temp, test_firm_2019_temp = generate_year_month_forFirm(train_firm_2019, valid_firm_2019, test_firm_2019)
train_firm_2020_temp, valid_firm_2020_temp, test_firm_2020_temp = generate_year_month_forFirm(train_firm_2020, valid_firm_2020, test_firm_2020)
train_firm_2021_temp, valid_firm_2021_temp, test_firm_2021_temp = generate_year_month_forFirm(train_firm_2021, valid_firm_2021, test_firm_2021)

In [ ]:
train_2018 = pd.merge(train_firm_2018_temp, train_macro_2018_temp, on=['year', 'month'], how='left')
valid_2018 = pd.merge(valid_firm_2018_temp, valid_macro_2018_temp, on=['year', 'month'], how='left')
test_2018 = pd.merge(test_firm_2018_temp, test_macro_2018_temp, on=['year', 'month'], how='left')

train_2019 = pd.merge(train_firm_2019_temp, train_macro_2019_temp, on=['year', 'month'], how='left')
valid_2019 = pd.merge(valid_firm_2019_temp, valid_macro_2019_temp, on=['year', 'month'], how='left')
test_2019 = pd.merge(test_firm_2019_temp, test_macro_2019_temp, on=['year', 'month'], how='left')

train_2020 = pd.merge(train_firm_2020_temp, train_macro_2020_temp, on=['year', 'month'], how='left')
valid_2020 = pd.merge(valid_firm_2020_temp, valid_macro_2020_temp, on=['year', 'month'], how='left')
test_2020 = pd.merge(test_firm_2020_temp, test_macro_2020_temp, on=['year', 'month'], how='left')

train_2021 = pd.merge(train_firm_2021_temp, train_macro_2021_temp, on=['year', 'month'], how='left')
valid_2021 = pd.merge(valid_firm_2021_temp, valid_macro_2021_temp, on=['year', 'month'], how='left')
test_2021 = pd.merge(test_firm_2021_temp, test_macro_2021_temp, on=['year', 'month'], how='left')

In [ ]:
train_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

In [ ]:
print(sum(train_2018.isnull().sum()))
print(sum(test_2018.isnull().sum()))
print(sum(valid_2018.isnull().sum()))

print(sum(train_2019.isnull().sum()))
print(sum(test_2019.isnull().sum()))
print(sum(valid_2019.isnull().sum()))

print(sum(train_2020.isnull().sum()))
print(sum(test_2020.isnull().sum()))
print(sum(valid_2020.isnull().sum()))

print(sum(train_2021.isnull().sum()))
print(sum(test_2021.isnull().sum()))
print(sum(valid_2021.isnull().sum()))

0
0
0
0
0
0
0
0
0
0
0
0

In [ ]:
train_macro_2018_temp

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19,year,month
0,1997-01-01,0.070149,0.026641,-0.084782,0.022162,-0.014845,-0.147834,0.063682,0.074618,0.039699,...,0.002767,-0.029662,-0.100859,-0.035114,0.100308,0.096447,0.032497,-0.025069,1997,1
1,1997-02-01,0.070096,0.028521,-0.080924,0.023861,-0.011429,-0.144107,0.062332,0.072179,0.039941,...,0.003310,-0.028290,-0.101918,-0.033484,0.098883,0.097605,0.031811,-0.023289,1997,2
2,1997-03-01,0.074675,0.032451,-0.081469,0.024248,-0.009215,-0.140306,0.063603,0.072668,0.044113,...,0.004421,-0.022812,-0.098573,-0.032283,0.095027,0.101236,0.037928,-0.025956,1997,3
3,1997-04-01,0.074176,0.029853,-0.083413,0.024465,-0.006169,-0.140812,0.065021,0.072021,0.044765,...,0.005783,-0.021139,-0.097457,-0.030115,0.096540,0.101212,0.038515,-0.026322,1997,4
4,1997-05-01,0.075383,0.025085,-0.090750,0.024673,-0.001685,-0.143357,0.066440,0.074132,0.045670,...,0.010062,-0.024030,-0.102989,-0.034086,0.095300,0.101363,0.039429,-0.027126,1997,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2014-08-01,0.092203,0.014796,-0.065993,-0.006009,-0.004482,-0.119058,0.058297,0.079264,0.045877,...,0.014589,-0.037410,-0.096965,-0.052499,0.081737,0.098911,0.031273,0.005789,2014,8
212,2014-09-01,0.094048,0.013823,-0.062257,-0.005608,-0.010076,-0.120749,0.050690,0.082587,0.049286,...,0.015115,-0.034019,-0.096837,-0.051169,0.082248,0.098569,0.029388,0.005349,2014,9
213,2014-10-01,0.088064,0.012511,-0.057809,-0.002092,-0.008500,-0.118926,0.052133,0.079987,0.047129,...,0.014144,-0.035067,-0.099852,-0.051980,0.081985,0.101247,0.030015,0.002896,2014,10
214,2014-11-01,0.092617,0.011348,-0.052634,-0.000958,-0.010778,-0.116099,0.052263,0.079566,0.040323,...,0.011663,-0.039779,-0.099824,-0.056204,0.082954,0.099119,0.028078,0.001192,2014,11
215,2014-12-01,0.088281,0.012987,-0.053589,-0.001348,-0.014115,-0.115602,0.050271,0.084040,0.041860,...,0.016558,-0.036471,-0.099846,-0.049030,0.084147,0.097920,0.025161,0.003549,2014,12

In [ ]:
train_firm_2018_temp

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19,month
0,ERTS,16721,75828,7372,3.0,11.0,36,1997,0.064718,1997-01-31,...,-0.007866,0.023190,-0.168285,-0.121665,-0.038322,-0.084682,-0.117417,-0.006333,0.107252,1
1,BMCS,14650,11976,7372,3.0,11.0,36,1997,0.048338,1997-01-31,...,-0.016959,0.025945,-0.175594,-0.120998,-0.043793,-0.091056,-0.118346,-0.005521,0.112488,1
2,LOW,6829,61399,5211,1.0,11.0,43,1997,-0.068632,1997-01-31,...,-0.014530,0.025004,-0.173039,-0.132915,-0.045645,-0.091474,-0.115696,-0.006687,0.123626,1
3,NKE,7906,57665,3021,1.0,11.0,10,1997,0.139583,1997-01-31,...,-0.023995,0.030466,-0.171475,-0.120554,-0.037044,-0.110117,-0.132952,-0.001920,0.108977,1
4,CPC,61404,82295,7500,1.0,11.0,33,1997,0.014925,1997-01-31,...,-0.034333,0.026528,-0.172744,-0.121261,-0.049424,-0.100359,-0.121147,0.000458,0.118068,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200964,NOC,7985,24766,3812,1.0,11.0,37,2014,0.045838,2014-12-31,...,-0.020363,0.029617,-0.184254,-0.114508,-0.045516,-0.087337,-0.126549,-0.008538,0.113358,12
200965,CVX,2991,14541,2911,1.0,11.0,30,2014,0.030403,2014-12-31,...,-0.031406,0.020202,-0.165850,-0.117160,-0.033731,-0.110053,-0.128346,0.000837,0.108359,12
200966,NOV,63892,84032,3533,1.0,11.0,21,2014,-0.015662,2014-12-31,...,-0.028163,0.029501,-0.187490,-0.113842,-0.049172,-0.094033,-0.127666,-0.006647,0.111515,12
200967,APO,184254,12591,6282,1.0,11.0,48,2014,-0.035188,2014-12-31,...,-0.034797,0.027056,-0.172068,-0.124870,-0.042095,-0.095095,-0.112806,-0.001466,0.122732,12
200968,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,-0.021195,0.020401,-0.178642,-0.124031,-0.047027,-0.089720,-0.111678,-0.008424,0.117021,12

## **데이터 저장**

In [ ]:
## Save
output_file_path = os.path.join(base_path, 'mergedData')

train_2018.to_csv(os.path.join(output_file_path, 'train2018.csv'), index=False)
valid_2018.to_csv(os.path.join(output_file_path, 'valid2018.csv'), index=False)
test_2018.to_csv(os.path.join(output_file_path, 'test2018.csv'), index=False)

train_2019.to_csv(os.path.join(output_file_path, 'train2019.csv'), index=False)
valid_2019.to_csv(os.path.join(output_file_path, 'valid2019.csv'), index=False)
test_2019.to_csv(os.path.join(output_file_path, 'test2019.csv'), index=False)

train_2020.to_csv(os.path.join(output_file_path, 'train2020.csv'), index=False)
valid_2020.to_csv(os.path.join(output_file_path, 'valid2020.csv'), index=False)
test_2020.to_csv(os.path.join(output_file_path, 'test2020.csv'), index=False)

train_2021.to_csv(os.path.join(output_file_path, 'train2021.csv'), index=False)
valid_2021.to_csv(os.path.join(output_file_path, 'valid2021.csv'), index=False)
test_2021.to_csv(os.path.join(output_file_path, 'test2021.csv'), index=False)