## **설정**

In [16]:
## Google Drive Amount
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
## Import libaries
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
## Setting
base_path = '/content/drive/MyDrive/CS/'

## **데이터 불러오기**

### **Firm**

In [26]:
## Load the data
file_path = os.path.join(base_path, 'hidden_states', 'CNNLSTM_Firm_simple')

train_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_20_20_Firm.csv'))

In [27]:
train_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,ERTS,16721,75828,7372,3.0,11.0,36,1997,0.064718,1997-01-31,...,0.028291,-0.007866,0.023190,-0.168285,-0.121665,-0.038322,-0.084682,-0.117417,-0.006333,0.107252
1,BMCS,14650,11976,7372,3.0,11.0,36,1997,0.048338,1997-01-31,...,0.032954,-0.016959,0.025945,-0.175594,-0.120998,-0.043793,-0.091056,-0.118346,-0.005521,0.112488
2,LOW,6829,61399,5211,1.0,11.0,43,1997,-0.068632,1997-01-31,...,0.035294,-0.014530,0.025004,-0.173039,-0.132915,-0.045645,-0.091474,-0.115696,-0.006687,0.123626
3,NKE,7906,57665,3021,1.0,11.0,10,1997,0.139583,1997-01-31,...,0.022729,-0.023995,0.030466,-0.171475,-0.120554,-0.037044,-0.110117,-0.132952,-0.001920,0.108977
4,CPC,61404,82295,7500,1.0,11.0,33,1997,0.014925,1997-01-31,...,0.027012,-0.034333,0.026528,-0.172744,-0.121261,-0.049424,-0.100359,-0.121147,0.000458,0.118068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200964,NOC,7985,24766,3812,1.0,11.0,37,2014,0.045838,2014-12-31,...,0.028322,-0.020363,0.029617,-0.184254,-0.114508,-0.045516,-0.087337,-0.126549,-0.008538,0.113358
200965,CVX,2991,14541,2911,1.0,11.0,30,2014,0.030403,2014-12-31,...,-0.004557,-0.031406,0.020202,-0.165850,-0.117160,-0.033731,-0.110053,-0.128346,0.000837,0.108359
200966,NOV,63892,84032,3533,1.0,11.0,21,2014,-0.015662,2014-12-31,...,0.024741,-0.028163,0.029501,-0.187490,-0.113842,-0.049172,-0.094033,-0.127666,-0.006647,0.111515
200967,APO,184254,12591,6282,1.0,11.0,48,2014,-0.035188,2014-12-31,...,0.027518,-0.034797,0.027056,-0.172068,-0.124870,-0.042095,-0.095095,-0.112806,-0.001466,0.122732
200968,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,0.037704,-0.021195,0.020401,-0.178642,-0.124031,-0.047027,-0.089720,-0.111678,-0.008424,0.117021

In [28]:
valid_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2015,-0.074988,2015-01-31,...,0.026567,-0.016915,0.025953,-0.171181,-0.112156,-0.039687,-0.104199,-0.127550,-0.007495,0.102085
1,LEN,6669,52708,1531,1.0,11.0,18,2015,0.003124,2015-01-31,...,0.016007,-0.024501,0.023155,-0.180788,-0.113822,-0.043913,-0.100784,-0.135893,-0.005865,0.109427
2,LH,14960,12062,8071,1.0,11.0,11,2015,0.063763,2015-01-31,...,0.035078,-0.022535,0.028517,-0.177842,-0.115206,-0.046598,-0.095281,-0.115647,-0.010728,0.109484
3,LII,122380,87034,3585,1.0,11.0,21,2015,0.034080,2015-01-31,...,0.034646,-0.019149,0.022177,-0.180713,-0.123819,-0.049908,-0.087230,-0.116596,-0.008228,0.117506
4,ATR,28176,79133,3089,1.0,11.0,15,2015,-0.051616,2015-01-31,...,0.035715,-0.022084,0.025698,-0.179924,-0.121552,-0.048855,-0.089112,-0.117722,-0.007429,0.116795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34686,NEU,4462,42550,2860,1.0,11.0,14,2017,-0.003445,2017-12-31,...,0.034292,-0.018306,0.023190,-0.178181,-0.124788,-0.044017,-0.091220,-0.116545,-0.007320,0.117605
34687,NEM,7881,21207,1040,1.0,11.0,27,2017,0.016356,2017-12-31,...,0.028763,-0.021891,0.021246,-0.181541,-0.114759,-0.044341,-0.097377,-0.129094,-0.005299,0.109074
34688,NEE,4517,24205,4911,1.0,11.0,31,2017,-0.011706,2017-12-31,...,0.019930,-0.027107,0.025571,-0.179420,-0.121367,-0.043505,-0.097075,-0.123316,-0.006829,0.116957
34689,NOC,7985,24766,3812,1.0,11.0,37,2017,0.001659,2017-12-31,...,0.029602,-0.019504,0.028004,-0.180424,-0.119011,-0.047249,-0.093908,-0.119810,-0.011278,0.110710
34690,ZTS,13721,13788,2834,1.0,11.0,13,2017,-0.003458,2017-12-31,...,0.035575,-0.011329,0.023760,-0.180566,-0.124087,-0.042748,-0.082984,-0.116031,-0.009348,0.114566

In [29]:
test_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2018,0.096461,2018-01-31,...,0.035436,-0.015706,0.028321,-0.176203,-0.114643,-0.045251,-0.098269,-0.114701,-0.012483,0.104588
1,LLL,110685,86021,3812,1.0,11.0,37,2018,0.073844,2018-01-31,...,0.031223,-0.022190,0.029893,-0.181655,-0.118415,-0.046082,-0.089001,-0.120674,-0.008757,0.115599
2,LLY,6730,50876,2834,1.0,11.0,13,2018,-0.035638,2018-01-31,...,0.027470,-0.013187,0.023839,-0.178150,-0.124271,-0.041893,-0.093218,-0.121877,-0.010802,0.112201
3,LM,6653,65330,6282,1.0,11.0,48,2018,0.015245,2018-01-31,...,0.040769,-0.020485,0.030661,-0.176477,-0.113864,-0.046428,-0.091919,-0.119390,-0.007562,0.110765
4,LMT,6774,21178,3760,1.0,11.0,26,2018,0.105280,2018-01-31,...,0.014493,-0.012252,0.025593,-0.172696,-0.124126,-0.033631,-0.101393,-0.129580,-0.011280,0.108928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11560,AKAM,125595,87299,7370,3.0,11.0,36,2018,-0.111564,2018-12-31,...,0.041080,-0.018627,0.022229,-0.177067,-0.121872,-0.050269,-0.094039,-0.105799,-0.011501,0.113171
11561,SLM,20430,66325,6141,3.0,11.0,45,2018,-0.190847,2018-12-31,...,0.031181,-0.029544,0.024388,-0.179225,-0.127731,-0.045825,-0.089269,-0.113244,-0.004208,0.123345
11562,FCX,14590,81774,1000,1.0,11.0,28,2018,-0.136516,2018-12-31,...,0.030963,-0.024622,0.018736,-0.177877,-0.128327,-0.045771,-0.094385,-0.114665,-0.007811,0.125633
11563,SNAP,30091,16595,7370,1.0,11.0,36,2018,-0.153610,2018-12-31,...,0.017286,-0.012426,0.017683,-0.163788,-0.107012,-0.030614,-0.083088,-0.121814,-0.018666,0.086257
11564,ZTS,13721,13788,2834,1.0,11.0,13,2018,-0.088740,2018-12-31,...,0.037183,-0.016096,0.023275,-0.179821,-0.123490,-0.048574,-0.093133,-0.112396,-0.012563,0.113149

In [9]:
200969+34691+11565

247225

In [15]:
firm1000=pd.read_csv('/content/drive/MyDrive/CS/myData/firm_top1000.csv')
firm1000['date']=pd.to_datetime(firm1000['date'])
firm1000[(firm1000['date'].dt.year>=1997) & (firm1000['date'].dt.year<=2018)]

,ticker,gvkey,permno,sic,ret,exchcd,shrcd,adm,bm_ia,herf,...,rd_sale,rdm,rna,roa,roe,rsup,sgr,sp,date,ffi49
3528,AAL,1045,21020,4512,0.127273,3.0,11.0,0.000004,0.874498,0.090561,...,0.324873,0.000008,-0.008577,-0.012862,0.121560,0.000489,-0.005645,0.002067,1997-04-30,41
3529,AAPL,1690,14593,3663,-0.022556,3.0,11.0,0.000088,2.172032,0.408549,...,0.061426,0.000292,0.023417,-0.022451,-0.059406,0.000007,0.174376,0.004747,1997-02-28,37
3530,AAPL,1690,14593,3663,0.123077,3.0,11.0,0.000090,2.222156,0.408549,...,0.061426,0.000298,-0.004670,-0.022451,-0.059406,-0.000020,-0.162363,0.004857,1997-03-31,37
3531,AAPL,1690,14593,3663,-0.068493,3.0,11.0,0.000079,1.949835,0.408549,...,0.061426,0.000262,0.017374,-0.022451,-0.059406,-0.000006,0.042429,0.004262,1997-04-30,37
3532,AAPL,1690,14593,3663,-0.022059,3.0,11.0,0.000085,2.093205,0.408549,...,0.068074,0.000279,0.025886,-0.131991,-0.344023,0.000067,1.229803,0.004101,1997-05-31,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250748,ZTS,13721,13788,2834,0.047641,1.0,11.0,0.000004,0.129210,0.100809,...,0.071324,0.000009,0.066959,0.040997,0.198870,0.000003,0.093643,0.000130,2018-08-31,13
250749,ZTS,13721,13788,2834,0.010596,1.0,11.0,0.000004,0.123857,0.100809,...,0.071324,0.000009,0.066959,0.040997,0.198870,0.000003,0.093643,0.000125,2018-09-30,13
250750,ZTS,13721,13788,2834,-0.015400,1.0,11.0,0.000003,0.122558,0.100809,...,0.071324,0.000009,0.066959,0.040997,0.198870,0.000003,0.093643,0.000124,2018-10-31,13
250751,ZTS,13721,13788,2834,0.042662,1.0,11.0,0.000004,0.124475,0.100809,...,0.072309,0.000009,0.069333,0.044189,0.195918,0.000003,0.109548,0.000129,2018-11-30,13
250752,ZTS,13721,13788,2834,-0.088740,1.0,11.0,0.000003,0.119884,0.100809,...,0.072309,0.000009,0.069333,0.044189,0.195918,0.000003,0.109548,0.000124,2018-12-31,13

### **Macro**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'hidden_states', 'CNN_BiLSTM_macro')

train_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_50_20_macro.csv'))

train_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_50_20_macro.csv'))

train_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_50_20_macro.csv'))

train_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_50_20_macro.csv'))

In [ ]:
train_macro_2018

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,1997-12-01,0.091517,-0.027015,-0.003873,-0.028873,-0.093428,-0.136721,0.043148,0.063463,-0.102444,...,-0.082506,-0.116688,0.001808,0.009426,-0.075297,0.107003,0.027744,0.036680,0.017056,-0.082583
1,1998-01-01,0.089603,-0.027332,-0.003186,-0.025108,-0.091325,-0.133605,0.042654,0.062252,-0.100757,...,-0.080383,-0.118437,0.003409,0.010893,-0.073883,0.106601,0.028652,0.037948,0.016547,-0.083554
2,1998-02-01,0.089596,-0.026988,-0.003939,-0.025411,-0.090299,-0.131793,0.042435,0.060520,-0.103230,...,-0.083732,-0.118480,0.001520,0.009696,-0.073881,0.107486,0.028597,0.039478,0.018072,-0.084624
3,1998-03-01,0.089236,-0.028089,-0.004381,-0.026648,-0.090105,-0.128808,0.043452,0.061639,-0.102257,...,-0.083119,-0.118899,0.000662,0.011103,-0.076296,0.108786,0.026684,0.036264,0.017645,-0.082526
4,1998-04-01,0.091397,-0.030860,-0.003927,-0.028978,-0.092239,-0.129604,0.042824,0.061088,-0.097913,...,-0.082971,-0.115903,-0.002664,0.011264,-0.079392,0.107063,0.026810,0.034492,0.015989,-0.086510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,2014-08-01,0.117568,-0.029772,0.029692,-0.046030,-0.127660,-0.147604,0.017055,0.046992,-0.094271,...,-0.110373,-0.108341,-0.010990,-0.024552,-0.077243,0.102323,0.054438,0.064144,0.011754,-0.092376
201,2014-09-01,0.118297,-0.029484,0.028391,-0.047782,-0.128366,-0.151101,0.019653,0.048574,-0.096101,...,-0.112033,-0.108202,-0.011445,-0.023990,-0.075969,0.102163,0.052287,0.061196,0.010182,-0.090941
202,2014-10-01,0.115283,-0.027599,0.028317,-0.045495,-0.127615,-0.146834,0.017973,0.045339,-0.097207,...,-0.110892,-0.107472,-0.010807,-0.025474,-0.074201,0.102663,0.052742,0.063190,0.011034,-0.091577
203,2014-11-01,0.116463,-0.030702,0.028740,-0.046704,-0.131487,-0.149701,0.020297,0.044547,-0.097849,...,-0.112113,-0.109092,-0.010058,-0.023575,-0.073937,0.104572,0.050074,0.063685,0.009854,-0.094264
204,2014-12-01,0.115470,-0.028425,0.027096,-0.047880,-0.132207,-0.150645,0.021598,0.044664,-0.099160,...,-0.114099,-0.109001,-0.009708,-0.023436,-0.074454,0.103780,0.049066,0.065009,0.010866,-0.095283

In [ ]:
valid_macro_2018

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,2015-01-01,0.116211,-0.026167,0.027116,-0.047586,-0.134975,-0.152904,0.022517,0.045429,-0.101271,...,-0.113462,-0.110272,-0.009163,-0.025433,-0.073092,0.105288,0.049321,0.063503,0.011275,-0.094943
1,2015-02-01,0.114084,-0.027881,0.027196,-0.046378,-0.134106,-0.152315,0.023694,0.043905,-0.101716,...,-0.112055,-0.109793,-0.006459,-0.027404,-0.071516,0.105213,0.050040,0.061405,0.011429,-0.092406
2,2015-03-01,0.113969,-0.028860,0.027998,-0.047471,-0.134380,-0.152168,0.024159,0.041569,-0.098590,...,-0.111835,-0.108241,-0.005384,-0.026996,-0.070971,0.104187,0.053520,0.060865,0.012811,-0.092672
3,2015-04-01,0.118452,-0.032285,0.026490,-0.051359,-0.133037,-0.154628,0.023820,0.044258,-0.096629,...,-0.116617,-0.107046,-0.006622,-0.025972,-0.072631,0.103927,0.050920,0.062250,0.015159,-0.095242
4,2015-05-01,0.120780,-0.030122,0.024858,-0.048318,-0.139204,-0.161922,0.027096,0.047020,-0.097237,...,-0.116058,-0.107137,-0.009301,-0.029256,-0.067453,0.102632,0.053609,0.062558,0.013102,-0.098601
5,2015-06-01,0.116562,-0.027646,0.023450,-0.047803,-0.132542,-0.153860,0.023359,0.046242,-0.096750,...,-0.116230,-0.108119,-0.010940,-0.025539,-0.067921,0.105130,0.046207,0.062867,0.017569,-0.096295
6,2015-07-01,0.113066,-0.028451,0.024407,-0.043060,-0.132616,-0.153762,0.025613,0.047119,-0.103923,...,-0.111850,-0.116309,-0.011911,-0.023576,-0.067490,0.107475,0.046450,0.068293,0.019182,-0.094954
7,2015-08-01,0.114880,-0.028919,0.027642,-0.045966,-0.132851,-0.155755,0.028927,0.045663,-0.102280,...,-0.115607,-0.114632,-0.011887,-0.024983,-0.071247,0.104378,0.048905,0.068895,0.014947,-0.096211
8,2015-09-01,0.115057,-0.030026,0.025709,-0.046877,-0.130085,-0.156093,0.029648,0.042131,-0.104825,...,-0.114153,-0.114967,-0.010396,-0.021698,-0.069684,0.106061,0.050872,0.067858,0.016067,-0.098045
9,2015-10-01,0.117276,-0.033240,0.027455,-0.048519,-0.133021,-0.159478,0.031474,0.044843,-0.104407,...,-0.113636,-0.119013,-0.012665,-0.021516,-0.070440,0.108635,0.051127,0.069548,0.017283,-0.099229
10,2015-11-01,0.118404,-0.031712,0.025927,-0.048920,-0.131475,-0.160391,0.031901,0.043047,-0.102393,...,-0.112481,-0.116210,-0.011753,-0.021920,-0.070099,0.104361,0.053537,0.070619,0.017742,-0.100209
11,2015-12-01,0.119971,-0.032981,0.026510,-0.048637,-0.131768,-0.160680,0.032474,0.044549,-0.102222,...,-0.112173,-0.118366,-0.011520,-0.021429,-0.069244,0.106012,0.055113,0.071715,0.019312,-0.100834
12,2016-01-01,0.119111,-0.029558,0.024359,-0.047311,-0.131518,-0.159580,0.031860,0.046178,-0.106956,...,-0.113405,-0.120676,-0.011969,-0.022640,-0.070217,0.108234,0.051241,0.071739,0.019191,-0.101246
13,2016-02-01,0.117253,-0.032244,0.023277,-0.048051,-0.129594,-0.159122,0.032166,0.044020,-0.105129,...,-0.114533,-0.118453,-0.012510,-0.021075,-0.068975,0.106273,0.050229,0.069297,0.018433,-0.101420
14,2016-03-01,0.119434,-0.033517,0.024647,-0.051077,-0.127792,-0.156677,0.033316,0.042746,-0.105208,...,-0.116605,-0.118494,-0.013267,-0.022014,-0.071436,0.108238,0.051893,0.068687,0.016925,-0.098363
15,2016-04-01,0.121344,-0.032965,0.025361,-0.052839,-0.130625,-0.160048,0.032752,0.043723,-0.107822,...,-0.113550,-0.119672,-0.012423,-0.020462,-0.070100,0.107905,0.050937,0.067995,0.015760,-0.100523
16,2016-05-01,0.120136,-0.032273,0.028179,-0.051684,-0.133859,-0.161235,0.034018,0.041087,-0.107241,...,-0.111125,-0.120853,-0.012894,-0.022579,-0.068116,0.107959,0.051142,0.066461,0.015075,-0.096855
17,2016-06-01,0.117325,-0.030154,0.027396,-0.052122,-0.135999,-0.161093,0.033042,0.037721,-0.107687,...,-0.111450,-0.120283,-0.010930,-0.020561,-0.070752,0.107566,0.047900,0.063454,0.014632,-0.098420
18,2016-07-01,0.119462,-0.028160,0.027176,-0.051798,-0.138277,-0.164412,0.033433,0.040518,-0.109288,...,-0.111842,-0.120929,-0.008911,-0.022512,-0.070804,0.109144,0.047932,0.063195,0.014896,-0.098034
19,2016-08-01,0.116225,-0.029522,0.028827,-0.051688,-0.137914,-0.163278,0.035384,0.038742,-0.111431,...,-0.110670,-0.122022,-0.009148,-0.024440,-0.070257,0.108419,0.049101,0.063681,0.012784,-0.096427
20,2016-09-01,0.117072,-0.031345,0.028620,-0.054367,-0.141054,-0.166290,0.035947,0.037371,-0.111111,...,-0.112151,-0.118466,-0.007029,-0.025658,-0.071428,0.107287,0.047177,0.061179,0.012467,-0.098272
21,2016-10-01,0.117356,-0.037401,0.029972,-0.053640,-0.141638,-0.163553,0.035572,0.036635,-0.109142,...,-0.109008,-0.122020,-0.008583,-0.025774,-0.073942,0.104789,0.049131,0.061675,0.008915,-0.098664
22,2016-11-01,0.115870,-0.036614,0.026033,-0.052669,-0.137604,-0.165227,0.035725,0.037694,-0.113424,...,-0.106201,-0.124471,-0.009362,-0.025095,-0.070441,0.106840,0.047825,0.059398,0.011067,-0.095448
23,2016-12-01,0.115176,-0.035131,0.026320,-0.052318,-0.137521,-0.162399,0.035604,0.034167,-0.113966,...,-0.106040,-0.122945,-0.008401,-0.025069,-0.067768,0.107440,0.045025,0.057562,0.010585,-0.094559
24,2017-01-01,0.118118,-0.034703,0.028195,-0.054238,-0.139099,-0.165490,0.036110,0.033294,-0.112436,...,-0.103731,-0.123067,-0.007196,-0.023304,-0.071309,0.105629,0.047675,0.060506,0.011450,-0.099641
25,2017-02-01,0.120431,-0.034888,0.028234,-0.055773,-0.137539,-0.162945,0.036393,0.034096,-0.111852,...,-0.106612,-0.122146,-0.010841,-0.025562,-0.073618,0.104967,0.046051,0.061375,0.010719,-0.099097
26,2017-03-01,0.121419,-0.034528,0.029828,-0.054717,-0.136127,-0.162928,0.034618,0.039163,-0.110033,...,-0.106196,-0.122870,-0.011340,-0.025704,-0.073805,0.107281,0.050714,0.063822,0.010017,-0.099517
27,2017-04-01,0.122086,-0.034962,0.029192,-0.053897,-0.137454,-0.162073,0.034858,0.031808,-0.108057,...,-0.101471,-0.123548,-0.010750,-0.023059,-0.072446,0.107888,0.049672,0.060723,0.010955,-0.100567
28,2017-05-01,0.117933,-0.034033,0.029132,-0.053024,-0.137712,-0.163554,0.034626,0.032812,-0.111221,...,-0.103049,-0.123996,-0.008709,-0.024440,-0.072873,0.107239,0.048633,0.059374,0.011169,-0.098393
29,2017-06-01,0.119593,-0.031218,0.029465,-0.051876,-0.137092,-0.159937,0.032975,0.033928,-0.110581,...,-0.102681,-0.123151,-0.008422,-0.025562,-0.072395,0.109926,0.049696,0.057205,0.012799,-0.097884
30,2017-07-01,0.120378,-0.035849,0.031499,-0.053271,-0.138134,-0.160851,0.034257,0.035170,-0.109155,...,-0.103410,-0.124722,-0.007492,-0.025747,-0.073665,0.108593,0.051447,0.059180,0.011653,-0.096944
31,2017-08-01,0.120009,-0.031432,0.032829,-0.053388,-0.139730,-0.162409,0.032349,0.034065,-0.110221,...,-0.103397,-0.121747,-0.007568,-0.025720,-0.072024,0.108019,0.049911,0.056141,0.012374,-0.097288
32,2017-09-01,0.117715,-0.033794,0.035751,-0.051262,-0.144828,-0.161034,0.036494,0.031701,-0.111216,...,-0.102083,-0.126412,-0.009664,-0.029967,-0.074271,0.108031,0.048368,0.057575,0.010119,-0.097011
33,2017-10-01,0.119675,-0.033649,0.033511,-0.050973,-0.143244,-0.162485,0.035699,0.034562,-0.111640,...,-0.104941,-0.123120,-0.008195,-0.029781,-0.072241,0.110143,0.051719,0.058123,0.011371,-0.097059
34,2017-11-01,0.121056,-0.034620,0.033160,-0.053311,-0.142879,-0.162754,0.037403,0.031107,-0.113833,...,-0.103608,-0.127129,-0.009123,-0.027177,-0.073550,0.110688,0.048997,0.059482,0.012404,-0.097369
35,2017-12-01,0.119192,-0.033269,0.037669,-0.049878,-0.143802,-0.165000,0.037787,0.032801,-0.116292,...,-0.100644,-0.129459,-0.008068,-0.029979,-0.071930,0.108477,0.053151,0.063168,0.010847,-0.097652

In [ ]:
test_macro_2021

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,2021-01-01,0.146396,0.050129,0.038231,-0.085715,-0.094313,-0.135306,0.076059,0.102564,-0.176653,...,-0.214560,-0.134050,0.004032,0.084484,-0.113397,0.131656,-0.094957,0.268303,0.028341,-0.206550
1,2021-02-01,0.146591,0.043569,0.044929,-0.078791,-0.098430,-0.139923,0.086938,0.085165,-0.175269,...,-0.189946,-0.143792,-0.001270,0.068441,-0.106646,0.134264,-0.071722,0.267602,0.028820,-0.188313
2,2021-03-01,0.130636,0.012977,0.050254,-0.024774,-0.064451,-0.098586,0.091124,0.053590,-0.182047,...,-0.175487,-0.206121,0.030543,0.051799,-0.068608,0.183854,-0.090364,0.226344,0.027691,-0.110051
3,2021-04-01,0.131748,0.024099,0.024345,-0.036266,-0.084383,-0.106379,0.055071,0.070205,-0.177927,...,-0.154051,-0.187130,0.012668,0.040372,-0.081805,0.176162,-0.069146,0.178486,0.022467,-0.091512
4,2021-05-01,0.123511,0.034571,0.018867,-0.036869,-0.093983,-0.117443,0.049885,0.083788,-0.180052,...,-0.150703,-0.176822,0.022073,0.033896,-0.086248,0.163237,-0.057112,0.156224,0.016195,-0.069378
5,2021-06-01,0.109933,0.031971,0.010102,-0.036517,-0.084642,-0.107391,0.038281,0.092212,-0.184646,...,-0.145552,-0.168836,0.031280,0.044643,-0.083821,0.162669,-0.045721,0.159224,0.033368,-0.075352
6,2021-07-01,0.107783,0.041902,0.007822,-0.041887,-0.087036,-0.108112,0.043353,0.101600,-0.183477,...,-0.150059,-0.164974,0.021177,0.032203,-0.083545,0.160890,-0.045413,0.151163,0.030218,-0.063046
7,2021-08-01,0.114711,0.038192,0.012741,-0.049781,-0.082818,-0.110778,0.045173,0.097128,-0.180891,...,-0.152315,-0.164419,0.017266,0.027547,-0.085031,0.154743,-0.041341,0.142509,0.018309,-0.056638
8,2021-09-01,0.116992,0.039813,0.014824,-0.054370,-0.089736,-0.113085,0.045193,0.096536,-0.175161,...,-0.154711,-0.157972,0.012593,0.021658,-0.087974,0.151261,-0.037789,0.138738,0.015376,-0.057757
9,2021-10-01,0.116050,0.042879,0.011851,-0.058277,-0.087025,-0.113567,0.046424,0.095991,-0.181184,...,-0.155496,-0.158603,0.010945,0.021993,-0.087651,0.150910,-0.043732,0.135858,0.015536,-0.055091
10,2021-11-01,0.114211,0.041933,0.018630,-0.060806,-0.086420,-0.109456,0.044300,0.096537,-0.176328,...,-0.162614,-0.160522,0.014054,0.021549,-0.089974,0.148030,-0.043733,0.138649,0.013433,-0.052072
11,2021-12-01,0.112968,0.046155,0.019657,-0.063740,-0.084657,-0.111225,0.044119,0.101200,-0.180250,...,-0.164936,-0.162140,0.010642,0.022747,-0.088079,0.147856,-0.044607,0.133424,0.005079,-0.047463

## **병합**

In [10]:
def generate_year_month_forMacro(train, valid, test):
  ## Datetime 변환
  train['sasdate']=pd.to_datetime(train['sasdate'])
  valid['sasdate']=pd.to_datetime(valid['sasdate'])
  test['sasdate']=pd.to_datetime(test['sasdate'])

  ## Join할 year, month 변수 생성
  train['year'] = train['sasdate'].dt.year
  train['month'] = train['sasdate'].dt.month

  valid['year'] = valid['sasdate'].dt.year
  valid['month'] = valid['sasdate'].dt.month

  test['year'] = test['sasdate'].dt.year
  test['month'] = test['sasdate'].dt.month

  return(train, valid, test)

def generate_year_month_forFirm(train, valid, test):
  ## Datetime 변환
  train['date']=pd.to_datetime(train['date'])
  valid['date']=pd.to_datetime(valid['date'])
  test['date']=pd.to_datetime(test['date'])

  ## Join할 year, month 변수 생성
  train['year'] = train['date'].dt.year
  train['month'] = train['date'].dt.month

  valid['year'] = valid['date'].dt.year
  valid['month'] = valid['date'].dt.month

  test['year'] = test['date'].dt.year
  test['month'] = test['date'].dt.month

  return(train, valid, test)

In [ ]:
train_macro_2018_temp, valid_macro_2018_temp, test_macro_2018_temp = generate_year_month_forMacro(train_macro_2018, valid_macro_2018, test_macro_2018)
train_macro_2019_temp, valid_macro_2019_temp, test_macro_2019_temp = generate_year_month_forMacro(train_macro_2019, valid_macro_2019, test_macro_2019)
train_macro_2020_temp, valid_macro_2020_temp, test_macro_2020_temp = generate_year_month_forMacro(train_macro_2020, valid_macro_2020, test_macro_2020)
train_macro_2021_temp, valid_macro_2021_temp, test_macro_2021_temp = generate_year_month_forMacro(train_macro_2021, valid_macro_2021, test_macro_2021)

In [12]:
train_firm_2018_temp, valid_firm_2018_temp, test_firm_2018_temp = generate_year_month_forFirm(train_firm_2018, valid_firm_2018, test_firm_2018)
train_firm_2019_temp, valid_firm_2019_temp, test_firm_2019_temp = generate_year_month_forFirm(train_firm_2019, valid_firm_2019, test_firm_2019)
train_firm_2020_temp, valid_firm_2020_temp, test_firm_2020_temp = generate_year_month_forFirm(train_firm_2020, valid_firm_2020, test_firm_2020)
train_firm_2021_temp, valid_firm_2021_temp, test_firm_2021_temp = generate_year_month_forFirm(train_firm_2021, valid_firm_2021, test_firm_2021)

In [ ]:
train_2018 = pd.merge(train_firm_2018_temp, train_macro_2018_temp, on=['year', 'month'], how='left')
valid_2018 = pd.merge(valid_firm_2018_temp, valid_macro_2018_temp, on=['year', 'month'], how='left')
test_2018 = pd.merge(test_firm_2018_temp, test_macro_2018_temp, on=['year', 'month'], how='left')

train_2019 = pd.merge(train_firm_2019_temp, train_macro_2019_temp, on=['year', 'month'], how='left')
valid_2019 = pd.merge(valid_firm_2019_temp, valid_macro_2019_temp, on=['year', 'month'], how='left')
test_2019 = pd.merge(test_firm_2019_temp, test_macro_2019_temp, on=['year', 'month'], how='left')

train_2020 = pd.merge(train_firm_2020_temp, train_macro_2020_temp, on=['year', 'month'], how='left')
valid_2020 = pd.merge(valid_firm_2020_temp, valid_macro_2020_temp, on=['year', 'month'], how='left')
test_2020 = pd.merge(test_firm_2020_temp, test_macro_2020_temp, on=['year', 'month'], how='left')

train_2021 = pd.merge(train_firm_2021_temp, train_macro_2021_temp, on=['year', 'month'], how='left')
valid_2021 = pd.merge(valid_firm_2021_temp, valid_macro_2021_temp, on=['year', 'month'], how='left')
test_2021 = pd.merge(test_firm_2021_temp, test_macro_2021_temp, on=['year', 'month'], how='left')

In [ ]:
train_firm_2018_temp

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19,month
0,PAYX,8402,61621,8721,3.0,11.0,34,1997,-0.055358,1997-01-31,...,0.087831,0.126172,-0.074237,0.028274,0.089823,0.133543,0.015113,-0.078611,-0.156122,1
1,PRFT,13380,11382,5311,3.0,11.0,43,1997,-0.016949,1997-01-31,...,0.094102,0.134470,-0.080831,0.021583,0.093098,0.133558,0.002238,-0.073944,-0.174100,1
2,CTAS,3062,23660,7200,3.0,11.0,33,1997,-0.029787,1997-01-31,...,0.117593,0.129559,-0.061736,0.018068,0.098857,0.115819,-0.003376,-0.070271,-0.144927,1
3,MKG,6096,12511,3842,1.0,11.0,12,1997,-0.070822,1997-01-31,...,0.113305,0.123523,-0.055548,0.019629,0.099651,0.117579,0.004436,-0.068024,-0.144763,1
4,CTX,2845,53831,1531,1.0,11.0,18,1997,0.036545,1997-01-31,...,0.112515,0.127704,-0.058090,0.017527,0.103999,0.110126,-0.001419,-0.074218,-0.148810,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200953,ONNN,134932,88182,3674,3.0,11.0,37,2014,0.121816,2014-12-31,...,0.113250,0.123428,-0.052604,0.024961,0.095614,0.115208,0.009093,-0.071337,-0.134217,12
200954,OPK,61490,82567,8071,1.0,11.0,11,2014,0.192124,2014-12-31,...,0.112746,0.117403,-0.050854,0.039142,0.100690,0.120334,0.006907,-0.054407,-0.114141,12
200955,COP,8549,13928,1311,1.0,11.0,30,2014,0.045255,2014-12-31,...,0.115442,0.128246,-0.053342,0.023918,0.099470,0.118098,0.008810,-0.069616,-0.130340,12
200956,CPB,2663,25320,2030,1.0,11.0,2,2014,-0.028269,2014-12-31,...,0.111491,0.131021,-0.043307,0.023765,0.086400,0.111878,0.016384,-0.055306,-0.115454,12
200957,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,0.110484,0.128405,-0.055840,0.025347,0.098739,0.113706,0.002371,-0.067701,-0.135112,12

In [ ]:
train_macro_2018_temp

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19,year,month
0,1997-12-01,0.091517,-0.027015,-0.003873,-0.028873,-0.093428,-0.136721,0.043148,0.063463,-0.102444,...,0.001808,0.009426,-0.075297,0.107003,0.027744,0.036680,0.017056,-0.082583,1997,12
1,1998-01-01,0.089603,-0.027332,-0.003186,-0.025108,-0.091325,-0.133605,0.042654,0.062252,-0.100757,...,0.003409,0.010893,-0.073883,0.106601,0.028652,0.037948,0.016547,-0.083554,1998,1
2,1998-02-01,0.089596,-0.026988,-0.003939,-0.025411,-0.090299,-0.131793,0.042435,0.060520,-0.103230,...,0.001520,0.009696,-0.073881,0.107486,0.028597,0.039478,0.018072,-0.084624,1998,2
3,1998-03-01,0.089236,-0.028089,-0.004381,-0.026648,-0.090105,-0.128808,0.043452,0.061639,-0.102257,...,0.000662,0.011103,-0.076296,0.108786,0.026684,0.036264,0.017645,-0.082526,1998,3
4,1998-04-01,0.091397,-0.030860,-0.003927,-0.028978,-0.092239,-0.129604,0.042824,0.061088,-0.097913,...,-0.002664,0.011264,-0.079392,0.107063,0.026810,0.034492,0.015989,-0.086510,1998,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,2014-08-01,0.117568,-0.029772,0.029692,-0.046030,-0.127660,-0.147604,0.017055,0.046992,-0.094271,...,-0.010990,-0.024552,-0.077243,0.102323,0.054438,0.064144,0.011754,-0.092376,2014,8
201,2014-09-01,0.118297,-0.029484,0.028391,-0.047782,-0.128366,-0.151101,0.019653,0.048574,-0.096101,...,-0.011445,-0.023990,-0.075969,0.102163,0.052287,0.061196,0.010182,-0.090941,2014,9
202,2014-10-01,0.115283,-0.027599,0.028317,-0.045495,-0.127615,-0.146834,0.017973,0.045339,-0.097207,...,-0.010807,-0.025474,-0.074201,0.102663,0.052742,0.063190,0.011034,-0.091577,2014,10
203,2014-11-01,0.116463,-0.030702,0.028740,-0.046704,-0.131487,-0.149701,0.020297,0.044547,-0.097849,...,-0.010058,-0.023575,-0.073937,0.104572,0.050074,0.063685,0.009854,-0.094264,2014,11
204,2014-12-01,0.115470,-0.028425,0.027096,-0.047880,-0.132207,-0.150645,0.021598,0.044664,-0.099160,...,-0.009708,-0.023436,-0.074454,0.103780,0.049066,0.065009,0.010866,-0.095283,2014,12