## **설정**

In [ ]:
## Google Drive Amount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
## Import libaries
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
## Setting
base_path = '/content/drive/MyDrive/CS2/'

## **데이터 불러오기**

In [ ]:
## Load the data
file_path = os.path.join(base_path, 'Data', 'macro')

df2014 = pd.read_csv(os.path.join(file_path, '2015-01.csv'))
df2015 = pd.read_csv(os.path.join(file_path, '2016-01.csv'))
df2016 = pd.read_csv(os.path.join(file_path, '2017-01.csv'))
df2017 = pd.read_csv(os.path.join(file_path, '2018-01.csv'))
df2018 = pd.read_csv(os.path.join(file_path, '2019-01.csv'))
df2019 = pd.read_csv(os.path.join(file_path, '2020-01.csv'))
df2020 = pd.read_csv(os.path.join(file_path, '2021-01.csv'))
df2021 = pd.read_csv(os.path.join(file_path, '2022-01.csv'))

## **데이터 전처리**

In [ ]:
## 데이터 전처리

# 첫번째 행 제거
df_cleaned2014 = df2014.iloc[1:].copy()
df_cleaned2015 = df2015.iloc[1:].copy()
df_cleaned2016 = df2016.iloc[1:].copy()
df_cleaned2017 = df2017.iloc[1:].copy()
df_cleaned2018 = df2018.iloc[1:].copy()
df_cleaned2019 = df2019.iloc[1:].copy()
df_cleaned2020 = df2020.iloc[1:].copy()
df_cleaned2021 = df2021.iloc[1:].copy()

# 날짜 컬럼 처리
df_cleaned2014['sasdate'] = pd.to_datetime(df_cleaned2014['sasdate'])
df_cleaned2015['sasdate'] = pd.to_datetime(df_cleaned2015['sasdate'])
df_cleaned2016['sasdate'] = pd.to_datetime(df_cleaned2016['sasdate'])
df_cleaned2017['sasdate'] = pd.to_datetime(df_cleaned2017['sasdate'])
df_cleaned2018['sasdate'] = pd.to_datetime(df_cleaned2018['sasdate'])
df_cleaned2019['sasdate'] = pd.to_datetime(df_cleaned2019['sasdate'])
df_cleaned2020['sasdate'] = pd.to_datetime(df_cleaned2020['sasdate'])
df_cleaned2021['sasdate'] = pd.to_datetime(df_cleaned2021['sasdate'])

# 1996년~
df_cleaned2014 = df_cleaned2014[(df_cleaned2014['sasdate'] >= '1995-12-01')]
df_cleaned2015 = df_cleaned2015[(df_cleaned2015['sasdate'] >= '1995-12-01')]
df_cleaned2016 = df_cleaned2016[(df_cleaned2016['sasdate'] >= '1995-12-01')]
df_cleaned2017 = df_cleaned2017[(df_cleaned2017['sasdate'] >= '1995-12-01')]
df_cleaned2018 = df_cleaned2018[(df_cleaned2018['sasdate'] >= '1995-12-01')]
df_cleaned2019 = df_cleaned2019[(df_cleaned2019['sasdate'] >= '1995-12-01')]
df_cleaned2020 = df_cleaned2020[(df_cleaned2020['sasdate'] >= '1995-12-01')]
df_cleaned2021 = df_cleaned2021[(df_cleaned2021['sasdate'] >= '1995-12-01')]

### **공통 컬럼**
- 각 연도별로 컬럼 개수가 조금 다름

In [ ]:
print("2014년:", len(df_cleaned2014.columns))
print("2015년:", len(df_cleaned2015.columns))
print("2016년:", len(df_cleaned2016.columns))
print("2017년:", len(df_cleaned2017.columns))
print("2018년:", len(df_cleaned2018.columns))
print("2019년:", len(df_cleaned2019.columns))
print("2020년:", len(df_cleaned2020.columns))
print("2021년:", len(df_cleaned2021.columns))

2014년: 134
2015년: 135
2016년: 128
2017년: 128
2018년: 128
2019년: 128
2020년: 128
2021년: 127

In [ ]:
dataframes = [
    df_cleaned2018, df_cleaned2019, df_cleaned2020, df_cleaned2021
]

common_columns = set(dataframes[0].columns)
for df in dataframes[1:]:
    common_columns = common_columns.intersection(set(df.columns))

common_columns_list = sorted(list(common_columns))

In [30]:
len(common_columns_list)

124

In [ ]:
df2018_filtered = df_cleaned2018[common_columns_list].copy()
df2019_filtered = df_cleaned2019[common_columns_list].copy()
df2020_filtered = df_cleaned2020[common_columns_list].copy()
df2021_filtered = df_cleaned2021[common_columns_list].copy()

### **결측치 처리**

#### **결측치 확인**

In [ ]:
# 2018
null_counts = df2018_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
rows_with_null = df2018_filtered[df2018_filtered.isnull().any(axis=1)]
display(rows_with_null[['sasdate'] + null_columns_list])

,sasdate,ACOGNO,AMDMNOx,AMDMUOx,ANDENOx,BUSINVx,CMRMTSPLx,CONSPI,DDURRG3M086SBEA,DNDGRG3M086SBEA,...,PERMIT,PERMITMW,PERMITNE,PERMITS,PERMITW,RETAILx,RPI,S&P PE ratio,TOTRESNS,W875RX1
719,2018-11-01,NaN,250827.0,1181650.0,75364.0,NaN,NaN,0.164801,87.361,99.317,...,1328.0,177.0,120.0,708.0,323.0,513531.0,16369.553,NaN,1840.828,13590.5
720,2018-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 2019
null_counts = df2019_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
rows_with_null = df2019_filtered[df2019_filtered.isnull().any(axis=1)]
display(rows_with_null[['sasdate'] + null_columns_list])

,sasdate,ACOGNO,BUSINVx,CMRMTSPLx,CONSPI,DTCOLNVHFNM,DTCTHFNM,HWI,HWIURATIO,ISRATIOx,NONREVSL,S&P PE ratio,S&P div yield
730,2019-10-01,210916.0,2042842.0,1515625.0,0.163574,319414.40,735219.31,7361.0,1.256787,1.40,3074.78837,22.040969,NaN
731,2019-11-01,212644.0,2037431.0,1526868.0,0.163637,319615.72,735871.89,6800.0,1.170194,1.39,3089.73698,NaN,NaN
732,2019-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 2020
null_counts = df2020_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
rows_with_null = df2020_filtered[df2020_filtered.isnull().any(axis=1)]
display(rows_with_null[['sasdate'] + null_columns_list])

,sasdate,ACOGNO,BUSINVx,CMRMTSPLx,COMPAPFFx,CONSPI,CP3Mx,DTCOLNVHFNM,DTCTHFNM,HWI,HWIURATIO,ISRATIOx,NONREVSL,S&P PE ratio
736,2020-04-01,154232.0,1979748.0,1312811.0,NaN,0.147478,NaN,319875.22,713024.39,4996.0,0.216193,1.67,3110.77621,20.892608
743,2020-11-01,204363.0,1959898.0,1568472.0,0.07,0.164406,0.16,350127.01,734604.43,6527.0,0.608408,1.32,3198.01773,NaN
744,2020-12-01,NaN,NaN,NaN,0.08,NaN,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 2021
null_counts = df2021_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
rows_with_null = df2021_filtered[df2021_filtered.isnull().any(axis=1)]
display(rows_with_null[['sasdate'] + null_columns_list])

,sasdate,ACOGNO,BUSINVx,CMRMTSPLx,COMPAPFFx,CONSPI,CP3Mx,DTCOLNVHFNM,DTCTHFNM,HWI,HWIURATIO,ISRATIOx,NONREVSL,S&P PE ratio
736,2020-04-01,142998.0,1997639.0,1267304.0,NaN,0.148762,NaN,319875.22,713024.39,4630.0,0.200972,1.73,3119.80081,20.892608
755,2021-11-01,215309.0,2158162.0,1565491.0,0.06,0.161468,0.14,371479.59,759570.02,10562.0,1.552779,1.25,3377.33167,NaN
756,2021-12-01,NaN,NaN,NaN,0.09,NaN,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### **forward fill**

In [ ]:
# 2018
null_counts = df2018_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
df2018_filtered[null_columns_list] = df2018_filtered[null_columns_list].ffill()

In [ ]:
# 2019
null_counts = df2019_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
df2019_filtered[null_columns_list] = df2019_filtered[null_columns_list].ffill()

In [ ]:
# 2020
null_counts = df2020_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()

df2020_filtered['CP3Mx'] = df2020_filtered['CP3Mx'].ffill() # 결측치 처리 : CP3Mx
df2020_filtered['COMPAPFFx'] = df2020_filtered['COMPAPFFx'].fillna(df2020_filtered['CP3Mx'] - df2020_filtered['FEDFUNDS']) # 결측치 처리 : COMPAPFFx = CP3Mx- FEDFUNDS
df2020_filtered[null_columns_list] = df2020_filtered[null_columns_list].ffill()

In [ ]:
# 2021
null_counts = df2021_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()

df2021_filtered['CP3Mx'] = df2021_filtered['CP3Mx'].ffill()
df2021_filtered['COMPAPFFx'] = df2021_filtered['COMPAPFFx'].fillna(df2021_filtered['CP3Mx'] - df2021_filtered['FEDFUNDS']) # 결측치 처리 : COMPAPFFx = CP3Mx- FEDFUNDS
df2021_filtered[null_columns_list] = df2021_filtered[null_columns_list].ffill()

#### **결측치 재확인**

In [ ]:
# 2018
null_counts = df2018_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
rows_with_null = df2018_filtered[df2018_filtered.isnull().any(axis=1)]
display(rows_with_null[['sasdate'] + null_columns_list])

Empty DataFrame
Columns: [sasdate]
Index: []

In [ ]:
# 2019
null_counts = df2019_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
rows_with_null = df2019_filtered[df2019_filtered.isnull().any(axis=1)]
display(rows_with_null[['sasdate'] + null_columns_list])

Empty DataFrame
Columns: [sasdate]
Index: []

In [ ]:
# 2020
null_counts = df2020_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
rows_with_null = df2020_filtered[df2020_filtered.isnull().any(axis=1)]
display(rows_with_null[['sasdate'] + null_columns_list])

Empty DataFrame
Columns: [sasdate]
Index: []

In [ ]:
# 2021
null_counts = df2021_filtered.isnull().sum()
null_columns_list = null_counts[null_counts > 0].index.tolist()
rows_with_null = df2021_filtered[df2021_filtered.isnull().any(axis=1)]
display(rows_with_null[['sasdate'] + null_columns_list])

Empty DataFrame
Columns: [sasdate]
Index: []

### **시차(lag) 반영**
- 다음해의 1월에 당해 12월이 채워져 있지 않았다.
- lag 1 적용

In [ ]:
columns_to_lag1 = [col for col in common_columns_list if col not in ['sasdate']]
len(columns_to_lag1)

123

In [ ]:
def lag_df(df, columns_to_lag, n):
  for col in columns_to_lag :
    df[col] =df[col].shift(n)
  df = df[['sasdate'] + columns_to_lag]
  df = df[(df['sasdate'] >= '1996-07-01')]

  return(df)

In [ ]:
df2018_final = lag_df(df2018_filtered, columns_to_lag1, n=1)
df2019_final = lag_df(df2019_filtered, columns_to_lag1, n=1)
df2020_final = lag_df(df2020_filtered, columns_to_lag1, n=1)
df2021_final = lag_df(df2021_filtered, columns_to_lag1, n=1)

In [ ]:
# 결측치 없는지 확인
display(sum(df2021_final.isnull().sum()))

0

## **저장**

In [ ]:
df2018_final

,sasdate,AAA,AAAFFM,ACOGNO,AMDMNOx,AMDMUOx,ANDENOx,AWHMAN,AWOTMAN,BAA,...,USGOOD,USGOVT,USTPU,USTRADE,USWTRADE,W875RX1,WPSFD49207,WPSFD49502,WPSID61,WPSID62
451,1996-07-01,7.71,2.44,106932.0,164599.0,472134.0,54476.0,41.5,4.8,8.40,...,23399.0,19528.0,24239.0,14132.8,5517.8,7859.1,131.3,129.5,125.8,112.2
452,1996-08-01,7.65,2.25,108503.0,163588.0,476647.0,55301.0,41.4,4.8,8.35,...,23418.0,19547.0,24283.0,14163.3,5521.5,7850.9,131.2,129.4,125.5,114.6
453,1996-09-01,7.46,2.24,107775.0,157310.0,473958.0,50906.0,41.5,4.8,8.18,...,23479.0,19504.0,24308.0,14182.7,5535.5,7884.7,131.6,129.9,125.6,115.3
454,1996-10-01,7.66,2.36,109377.0,165442.0,476545.0,55893.0,41.6,4.9,8.35,...,23497.0,19567.0,24346.0,14208.5,5551.0,7915.4,131.7,130.0,126.1,112.7
455,1996-11-01,7.39,2.15,109918.0,165266.0,482916.0,55625.0,41.4,4.8,8.07,...,23546.0,19554.0,24414.0,14260.0,5569.9,7921.9,132.4,130.9,126.0,111.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,2018-08-01,3.87,1.96,213659.0,248571.0,1166061.0,75540.0,42.2,4.5,4.79,...,20701.0,22377.0,27782.0,15917.3,5984.2,13474.2,204.9,217.8,202.4,202.3
717,2018-09-01,3.88,1.97,213682.0,260223.0,1176807.0,81095.0,42.2,4.5,4.77,...,20750.0,22396.0,27836.0,15926.4,6004.8,13516.2,205.2,218.0,202.8,194.9
718,2018-10-01,3.98,2.03,215759.0,260178.0,1185282.0,78513.0,42.1,4.5,4.88,...,20787.0,22398.0,27837.0,15899.6,6007.5,13520.2,204.7,217.1,202.6,196.5
719,2018-11-01,4.14,1.95,216910.0,248939.0,1183352.0,74854.0,42.0,4.5,5.07,...,20851.0,22391.0,27861.0,15899.7,6013.1,13562.8,206.2,219.3,204.3,203.6
720,2018-12-01,4.22,2.02,216910.0,250827.0,1181650.0,75364.0,42.0,4.6,5.22,...,20878.0,22394.0,27929.0,15928.9,6022.4,13590.5,204.5,216.8,202.9,192.9

In [ ]:
## Save
output_file_path = os.path.join(base_path, 'myData')

df2018_final.to_csv(os.path.join(output_file_path, 'macro2018.csv'),index=False)
df2019_final.to_csv(os.path.join(output_file_path, 'macro2019.csv'),index=False)
df2020_final.to_csv(os.path.join(output_file_path, 'macro2020.csv'),index=False)
df2021_final.to_csv(os.path.join(output_file_path, 'macro2021.csv'),index=False)