- Macro HS : 20-10
- Firm HS : 20-20

## **설정**

In [1]:
## Google Drive Amount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
## Import libaries
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
## Setting
base_path1 = '/content/drive/MyDrive/CS/'
base_path2 = '/content/drive/MyDrive/CS2/'

## **데이터 불러오기**

### **Firm**

In [4]:
## Load the data
file_path = os.path.join(base_path1, 'hidden_states', 'CNNLSTM_Firm_simple')

train_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_20_20_Firm.csv'))

In [5]:
train_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,ERTS,16721,75828,7372,3.0,11.0,36,1997,0.064718,1997-01-31,...,0.028291,-0.007866,0.023190,-0.168285,-0.121665,-0.038322,-0.084682,-0.117417,-0.006333,0.107252
1,BMCS,14650,11976,7372,3.0,11.0,36,1997,0.048338,1997-01-31,...,0.032954,-0.016959,0.025945,-0.175594,-0.120998,-0.043793,-0.091056,-0.118346,-0.005521,0.112488
2,LOW,6829,61399,5211,1.0,11.0,43,1997,-0.068632,1997-01-31,...,0.035294,-0.014530,0.025004,-0.173039,-0.132915,-0.045645,-0.091474,-0.115696,-0.006687,0.123626
3,NKE,7906,57665,3021,1.0,11.0,10,1997,0.139583,1997-01-31,...,0.022729,-0.023995,0.030466,-0.171475,-0.120554,-0.037044,-0.110117,-0.132952,-0.001920,0.108977
4,CPC,61404,82295,7500,1.0,11.0,33,1997,0.014925,1997-01-31,...,0.027012,-0.034333,0.026528,-0.172744,-0.121261,-0.049424,-0.100359,-0.121147,0.000458,0.118068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200964,NOC,7985,24766,3812,1.0,11.0,37,2014,0.045838,2014-12-31,...,0.028322,-0.020363,0.029617,-0.184254,-0.114508,-0.045516,-0.087337,-0.126549,-0.008538,0.113358
200965,CVX,2991,14541,2911,1.0,11.0,30,2014,0.030403,2014-12-31,...,-0.004557,-0.031406,0.020202,-0.165850,-0.117160,-0.033731,-0.110053,-0.128346,0.000837,0.108359
200966,NOV,63892,84032,3533,1.0,11.0,21,2014,-0.015662,2014-12-31,...,0.024741,-0.028163,0.029501,-0.187490,-0.113842,-0.049172,-0.094033,-0.127666,-0.006647,0.111515
200967,APO,184254,12591,6282,1.0,11.0,48,2014,-0.035188,2014-12-31,...,0.027518,-0.034797,0.027056,-0.172068,-0.124870,-0.042095,-0.095095,-0.112806,-0.001466,0.122732
200968,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,0.037704,-0.021195,0.020401,-0.178642,-0.124031,-0.047027,-0.089720,-0.111678,-0.008424,0.117021

In [6]:
valid_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2015,-0.074988,2015-01-31,...,0.026567,-0.016915,0.025953,-0.171181,-0.112156,-0.039687,-0.104199,-0.127550,-0.007495,0.102085
1,LEN,6669,52708,1531,1.0,11.0,18,2015,0.003124,2015-01-31,...,0.016007,-0.024501,0.023155,-0.180788,-0.113822,-0.043913,-0.100784,-0.135893,-0.005865,0.109427
2,LH,14960,12062,8071,1.0,11.0,11,2015,0.063763,2015-01-31,...,0.035078,-0.022535,0.028517,-0.177842,-0.115206,-0.046598,-0.095281,-0.115647,-0.010728,0.109484
3,LII,122380,87034,3585,1.0,11.0,21,2015,0.034080,2015-01-31,...,0.034646,-0.019149,0.022177,-0.180713,-0.123819,-0.049908,-0.087230,-0.116596,-0.008228,0.117506
4,ATR,28176,79133,3089,1.0,11.0,15,2015,-0.051616,2015-01-31,...,0.035715,-0.022084,0.025698,-0.179924,-0.121552,-0.048855,-0.089112,-0.117722,-0.007429,0.116795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34686,NEU,4462,42550,2860,1.0,11.0,14,2017,-0.003445,2017-12-31,...,0.034292,-0.018306,0.023190,-0.178181,-0.124788,-0.044017,-0.091220,-0.116545,-0.007320,0.117605
34687,NEM,7881,21207,1040,1.0,11.0,27,2017,0.016356,2017-12-31,...,0.028763,-0.021891,0.021246,-0.181541,-0.114759,-0.044341,-0.097377,-0.129094,-0.005299,0.109074
34688,NEE,4517,24205,4911,1.0,11.0,31,2017,-0.011706,2017-12-31,...,0.019930,-0.027107,0.025571,-0.179420,-0.121367,-0.043505,-0.097075,-0.123316,-0.006829,0.116957
34689,NOC,7985,24766,3812,1.0,11.0,37,2017,0.001659,2017-12-31,...,0.029602,-0.019504,0.028004,-0.180424,-0.119011,-0.047249,-0.093908,-0.119810,-0.011278,0.110710
34690,ZTS,13721,13788,2834,1.0,11.0,13,2017,-0.003458,2017-12-31,...,0.035575,-0.011329,0.023760,-0.180566,-0.124087,-0.042748,-0.082984,-0.116031,-0.009348,0.114566

In [7]:
test_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2018,0.096461,2018-01-31,...,0.035436,-0.015706,0.028321,-0.176203,-0.114643,-0.045251,-0.098269,-0.114701,-0.012483,0.104588
1,LLL,110685,86021,3812,1.0,11.0,37,2018,0.073844,2018-01-31,...,0.031223,-0.022190,0.029893,-0.181655,-0.118415,-0.046082,-0.089001,-0.120674,-0.008757,0.115599
2,LLY,6730,50876,2834,1.0,11.0,13,2018,-0.035638,2018-01-31,...,0.027470,-0.013187,0.023839,-0.178150,-0.124271,-0.041893,-0.093218,-0.121877,-0.010802,0.112201
3,LM,6653,65330,6282,1.0,11.0,48,2018,0.015245,2018-01-31,...,0.040769,-0.020485,0.030661,-0.176477,-0.113864,-0.046428,-0.091919,-0.119390,-0.007562,0.110765
4,LMT,6774,21178,3760,1.0,11.0,26,2018,0.105280,2018-01-31,...,0.014493,-0.012252,0.025593,-0.172696,-0.124126,-0.033631,-0.101393,-0.129580,-0.011280,0.108928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11560,AKAM,125595,87299,7370,3.0,11.0,36,2018,-0.111564,2018-12-31,...,0.041080,-0.018627,0.022229,-0.177067,-0.121872,-0.050269,-0.094039,-0.105799,-0.011501,0.113171
11561,SLM,20430,66325,6141,3.0,11.0,45,2018,-0.190847,2018-12-31,...,0.031181,-0.029544,0.024388,-0.179225,-0.127731,-0.045825,-0.089269,-0.113244,-0.004208,0.123345
11562,FCX,14590,81774,1000,1.0,11.0,28,2018,-0.136516,2018-12-31,...,0.030963,-0.024622,0.018736,-0.177877,-0.128327,-0.045771,-0.094385,-0.114665,-0.007811,0.125633
11563,SNAP,30091,16595,7370,1.0,11.0,36,2018,-0.153610,2018-12-31,...,0.017286,-0.012426,0.017683,-0.163788,-0.107012,-0.030614,-0.083088,-0.121814,-0.018666,0.086257
11564,ZTS,13721,13788,2834,1.0,11.0,13,2018,-0.088740,2018-12-31,...,0.037183,-0.016096,0.023275,-0.179821,-0.123490,-0.048574,-0.093133,-0.112396,-0.012563,0.113149

### **Macro**

In [8]:
## Load the data
file_path = os.path.join(base_path2, 'hidden_states', 'CNN_BiLSTM_macro')

train_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_20_10_macro.csv'))
valid_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_20_10_macro.csv'))
test_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_20_10_macro.csv'))

train_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_20_10_macro.csv'))
valid_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_20_10_macro.csv'))
test_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_20_10_macro.csv'))

train_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_20_10_macro.csv'))
valid_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_20_10_macro.csv'))
test_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_20_10_macro.csv'))

train_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_20_10_macro.csv'))
valid_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_20_10_macro.csv'))
test_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_20_10_macro.csv'))

In [9]:
train_macro_2018

,sasdate,hs_10_0,hs_10_1,hs_10_2,hs_10_3,hs_10_4,hs_10_5,hs_10_6,hs_10_7,hs_10_8,hs_10_9
0,1997-01-01,-0.064543,-0.105600,0.161519,-0.102919,-0.079828,0.039900,0.052555,0.170352,-0.093718,0.011993
1,1997-02-01,-0.065280,-0.105393,0.158503,-0.103024,-0.080269,0.041051,0.050893,0.169892,-0.091536,0.013273
2,1997-03-01,-0.063839,-0.107597,0.156827,-0.103878,-0.078832,0.043007,0.050671,0.173173,-0.091504,0.012816
3,1997-04-01,-0.065408,-0.110540,0.156606,-0.102309,-0.078543,0.044115,0.048243,0.173885,-0.092503,0.009471
4,1997-05-01,-0.065689,-0.106693,0.155967,-0.103517,-0.079762,0.045164,0.049001,0.174296,-0.090993,0.012133
...,...,...,...,...,...,...,...,...,...,...,...
211,2014-08-01,-0.052493,-0.105543,0.153189,-0.065142,-0.041434,0.027570,0.067321,0.170376,-0.067194,0.016650
212,2014-09-01,-0.053162,-0.102856,0.145749,-0.065079,-0.044546,0.032219,0.068743,0.169735,-0.062945,0.021990
213,2014-10-01,-0.054174,-0.102440,0.147937,-0.064903,-0.043882,0.031681,0.067615,0.171407,-0.068079,0.020454
214,2014-11-01,-0.056066,-0.100014,0.147666,-0.067999,-0.048929,0.034158,0.065755,0.170303,-0.068303,0.016019
215,2014-12-01,-0.056269,-0.101391,0.147476,-0.065181,-0.046686,0.034508,0.066257,0.172767,-0.070648,0.014156

In [10]:
valid_macro_2018

,sasdate,hs_10_0,hs_10_1,hs_10_2,hs_10_3,hs_10_4,hs_10_5,hs_10_6,hs_10_7,hs_10_8,hs_10_9
0,2015-01-01,-0.058056,-0.103253,0.148193,-0.067687,-0.044285,0.035468,0.067776,0.173873,-0.069953,0.015226
1,2015-02-01,-0.057240,-0.100963,0.147121,-0.063319,-0.045346,0.034389,0.066237,0.172703,-0.071509,0.016506
2,2015-03-01,-0.056966,-0.102555,0.148468,-0.063585,-0.042585,0.032982,0.065542,0.173830,-0.071895,0.014436
3,2015-04-01,-0.054827,-0.104480,0.147773,-0.062765,-0.041668,0.032317,0.066919,0.171913,-0.071347,0.015011
4,2015-05-01,-0.054443,-0.100329,0.150195,-0.064134,-0.043955,0.029702,0.068976,0.169643,-0.073356,0.016906
5,2015-06-01,-0.053946,-0.104318,0.149461,-0.065510,-0.043714,0.030170,0.071711,0.169444,-0.071135,0.016071
6,2015-07-01,-0.055644,-0.104319,0.149741,-0.068456,-0.045409,0.031736,0.069491,0.169911,-0.071421,0.014300
7,2015-08-01,-0.053631,-0.104062,0.151806,-0.067555,-0.042192,0.028067,0.073482,0.168713,-0.076443,0.014483
8,2015-09-01,-0.055500,-0.103168,0.147539,-0.066159,-0.039655,0.030357,0.073269,0.170408,-0.071164,0.013744
9,2015-10-01,-0.058839,-0.101774,0.150109,-0.069020,-0.042201,0.032684,0.072558,0.170437,-0.070644,0.011444
10,2015-11-01,-0.058431,-0.100956,0.145899,-0.065265,-0.034999,0.032933,0.071128,0.173796,-0.068254,0.012024
11,2015-12-01,-0.056526,-0.100751,0.150466,-0.069092,-0.038825,0.029300,0.073042,0.170129,-0.070555,0.013541
12,2016-01-01,-0.057450,-0.103825,0.149377,-0.065184,-0.041020,0.031462,0.070166,0.173165,-0.073978,0.014228
13,2016-02-01,-0.058131,-0.102095,0.148154,-0.067625,-0.040228,0.030958,0.070924,0.172856,-0.073688,0.014243
14,2016-03-01,-0.057806,-0.103204,0.148757,-0.065882,-0.037881,0.030567,0.071482,0.173931,-0.074406,0.012748
15,2016-04-01,-0.058235,-0.102038,0.154308,-0.068379,-0.038449,0.028821,0.073817,0.173570,-0.078020,0.013356
16,2016-05-01,-0.058666,-0.099318,0.152738,-0.067582,-0.036420,0.027129,0.072191,0.174110,-0.075963,0.014278
17,2016-06-01,-0.056426,-0.100416,0.155883,-0.067580,-0.037171,0.025179,0.075330,0.172483,-0.078292,0.014041
18,2016-07-01,-0.056634,-0.101644,0.156700,-0.070331,-0.036942,0.024899,0.077787,0.171361,-0.078025,0.013941
19,2016-08-01,-0.055797,-0.101346,0.154870,-0.066771,-0.032232,0.022458,0.075358,0.173181,-0.078419,0.014975
20,2016-09-01,-0.054135,-0.100657,0.157094,-0.066303,-0.033098,0.020941,0.079206,0.168940,-0.078991,0.013250
21,2016-10-01,-0.053172,-0.102764,0.159349,-0.065197,-0.032070,0.018332,0.077294,0.170660,-0.081216,0.014630
22,2016-11-01,-0.052095,-0.101577,0.155106,-0.062888,-0.030142,0.018862,0.076720,0.170451,-0.080133,0.015255
23,2016-12-01,-0.049688,-0.102774,0.154452,-0.060331,-0.030099,0.017488,0.075125,0.169561,-0.078901,0.015549
24,2017-01-01,-0.051165,-0.101632,0.153406,-0.061866,-0.033474,0.019448,0.075462,0.168251,-0.079983,0.015114
25,2017-02-01,-0.052723,-0.101073,0.154052,-0.063585,-0.032536,0.020907,0.074180,0.171546,-0.080108,0.015285
26,2017-03-01,-0.053693,-0.101601,0.158093,-0.066275,-0.033053,0.021290,0.076572,0.171724,-0.080001,0.013626
27,2017-04-01,-0.054222,-0.100989,0.156422,-0.065616,-0.032021,0.021448,0.077635,0.172578,-0.078247,0.018411
28,2017-05-01,-0.054026,-0.102448,0.161552,-0.068578,-0.031276,0.019350,0.081394,0.171185,-0.080472,0.013972
29,2017-06-01,-0.053614,-0.099494,0.157081,-0.063150,-0.031577,0.020780,0.078391,0.169892,-0.078702,0.017106
30,2017-07-01,-0.053551,-0.098495,0.159475,-0.064328,-0.029935,0.018535,0.081679,0.167747,-0.079328,0.015331
31,2017-08-01,-0.054055,-0.095130,0.158989,-0.064364,-0.032186,0.018495,0.081495,0.166946,-0.078832,0.017642
32,2017-09-01,-0.052902,-0.097753,0.159232,-0.064010,-0.031139,0.018372,0.082890,0.165748,-0.078750,0.014555
33,2017-10-01,-0.054096,-0.098320,0.161414,-0.063847,-0.028243,0.016893,0.081190,0.167420,-0.078939,0.014107
34,2017-11-01,-0.049781,-0.098562,0.160601,-0.063630,-0.030046,0.014943,0.084254,0.163432,-0.077239,0.015606
35,2017-12-01,-0.052182,-0.098378,0.159775,-0.062646,-0.028026,0.015799,0.082191,0.164493,-0.077231,0.015265

In [11]:
test_macro_2021

,sasdate,hs_10_0,hs_10_1,hs_10_2,hs_10_3,hs_10_4,hs_10_5,hs_10_6,hs_10_7,hs_10_8,hs_10_9
0,2021-01-01,-0.109333,-0.144661,0.148274,-0.147210,-0.071311,0.111958,0.080634,0.183173,-0.081779,-0.022084
1,2021-02-01,-0.103361,-0.143198,0.136768,-0.139386,-0.070438,0.113893,0.070996,0.182755,-0.077497,-0.015629
2,2021-03-01,-0.102436,-0.140558,0.138040,-0.137925,-0.074160,0.111279,0.068512,0.179024,-0.083647,-0.011707
3,2021-04-01,-0.098824,-0.140572,0.132124,-0.132616,-0.069012,0.113854,0.068244,0.179838,-0.078447,-0.007714
4,2021-05-01,-0.101499,-0.140608,0.133339,-0.136741,-0.075673,0.114273,0.066838,0.174007,-0.079965,-0.006909
5,2021-06-01,-0.099999,-0.147969,0.124039,-0.132245,-0.074576,0.121627,0.061294,0.180562,-0.071709,-0.008666
6,2021-07-01,-0.097062,-0.152663,0.119832,-0.132645,-0.076917,0.123843,0.061725,0.176987,-0.071096,-0.008594
7,2021-08-01,-0.098623,-0.162432,0.111328,-0.131023,-0.069579,0.130738,0.057339,0.185562,-0.066739,-0.009419
8,2021-09-01,-0.095063,-0.167022,0.111911,-0.131329,-0.075253,0.133053,0.056507,0.184779,-0.067178,-0.010512
9,2021-10-01,-0.092718,-0.171274,0.116358,-0.136176,-0.081409,0.129658,0.061554,0.184560,-0.072837,-0.011768
10,2021-11-01,-0.091797,-0.176900,0.115037,-0.135921,-0.082122,0.134176,0.062144,0.187205,-0.074203,-0.009198
11,2021-12-01,-0.089232,-0.181832,0.114397,-0.138157,-0.083329,0.135030,0.063348,0.186354,-0.076425,-0.008308

## **병합**

In [12]:
def generate_year_month_forMacro(train, valid, test):
  ## Datetime 변환
  train['sasdate']=pd.to_datetime(train['sasdate'])
  valid['sasdate']=pd.to_datetime(valid['sasdate'])
  test['sasdate']=pd.to_datetime(test['sasdate'])

  ## Join할 year, month 변수 생성
  train['year'] = train['sasdate'].dt.year
  train['month'] = train['sasdate'].dt.month

  valid['year'] = valid['sasdate'].dt.year
  valid['month'] = valid['sasdate'].dt.month

  test['year'] = test['sasdate'].dt.year
  test['month'] = test['sasdate'].dt.month

  return(train, valid, test)

def generate_year_month_forFirm(train, valid, test):
  ## Datetime 변환
  train['date']=pd.to_datetime(train['date'])
  valid['date']=pd.to_datetime(valid['date'])
  test['date']=pd.to_datetime(test['date'])

  ## Join할 year, month 변수 생성
  train['year'] = train['date'].dt.year
  train['month'] = train['date'].dt.month

  valid['year'] = valid['date'].dt.year
  valid['month'] = valid['date'].dt.month

  test['year'] = test['date'].dt.year
  test['month'] = test['date'].dt.month

  return(train, valid, test)

In [13]:
train_macro_2018_temp, valid_macro_2018_temp, test_macro_2018_temp = generate_year_month_forMacro(train_macro_2018, valid_macro_2018, test_macro_2018)
train_macro_2019_temp, valid_macro_2019_temp, test_macro_2019_temp = generate_year_month_forMacro(train_macro_2019, valid_macro_2019, test_macro_2019)
train_macro_2020_temp, valid_macro_2020_temp, test_macro_2020_temp = generate_year_month_forMacro(train_macro_2020, valid_macro_2020, test_macro_2020)
train_macro_2021_temp, valid_macro_2021_temp, test_macro_2021_temp = generate_year_month_forMacro(train_macro_2021, valid_macro_2021, test_macro_2021)

train_firm_2018_temp, valid_firm_2018_temp, test_firm_2018_temp = generate_year_month_forFirm(train_firm_2018, valid_firm_2018, test_firm_2018)
train_firm_2019_temp, valid_firm_2019_temp, test_firm_2019_temp = generate_year_month_forFirm(train_firm_2019, valid_firm_2019, test_firm_2019)
train_firm_2020_temp, valid_firm_2020_temp, test_firm_2020_temp = generate_year_month_forFirm(train_firm_2020, valid_firm_2020, test_firm_2020)
train_firm_2021_temp, valid_firm_2021_temp, test_firm_2021_temp = generate_year_month_forFirm(train_firm_2021, valid_firm_2021, test_firm_2021)

In [14]:
train_2018 = pd.merge(train_firm_2018_temp, train_macro_2018_temp, on=['year', 'month'], how='left')
valid_2018 = pd.merge(valid_firm_2018_temp, valid_macro_2018_temp, on=['year', 'month'], how='left')
test_2018 = pd.merge(test_firm_2018_temp, test_macro_2018_temp, on=['year', 'month'], how='left')

train_2019 = pd.merge(train_firm_2019_temp, train_macro_2019_temp, on=['year', 'month'], how='left')
valid_2019 = pd.merge(valid_firm_2019_temp, valid_macro_2019_temp, on=['year', 'month'], how='left')
test_2019 = pd.merge(test_firm_2019_temp, test_macro_2019_temp, on=['year', 'month'], how='left')

train_2020 = pd.merge(train_firm_2020_temp, train_macro_2020_temp, on=['year', 'month'], how='left')
valid_2020 = pd.merge(valid_firm_2020_temp, valid_macro_2020_temp, on=['year', 'month'], how='left')
test_2020 = pd.merge(test_firm_2020_temp, test_macro_2020_temp, on=['year', 'month'], how='left')

train_2021 = pd.merge(train_firm_2021_temp, train_macro_2021_temp, on=['year', 'month'], how='left')
valid_2021 = pd.merge(valid_firm_2021_temp, valid_macro_2021_temp, on=['year', 'month'], how='left')
test_2021 = pd.merge(test_firm_2021_temp, test_macro_2021_temp, on=['year', 'month'], how='left')

In [15]:
train_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

In [16]:
print(sum(train_2018.isnull().sum()))
print(sum(test_2018.isnull().sum()))
print(sum(valid_2018.isnull().sum()))

print(sum(train_2019.isnull().sum()))
print(sum(test_2019.isnull().sum()))
print(sum(valid_2019.isnull().sum()))

print(sum(train_2020.isnull().sum()))
print(sum(test_2020.isnull().sum()))
print(sum(valid_2020.isnull().sum()))

print(sum(train_2021.isnull().sum()))
print(sum(test_2021.isnull().sum()))
print(sum(valid_2021.isnull().sum()))

0
0
0
0
0
0
0
0
0
0
0
0

In [17]:
train_macro_2018_temp

,sasdate,hs_10_0,hs_10_1,hs_10_2,hs_10_3,hs_10_4,hs_10_5,hs_10_6,hs_10_7,hs_10_8,hs_10_9,year,month
0,1997-01-01,-0.064543,-0.105600,0.161519,-0.102919,-0.079828,0.039900,0.052555,0.170352,-0.093718,0.011993,1997,1
1,1997-02-01,-0.065280,-0.105393,0.158503,-0.103024,-0.080269,0.041051,0.050893,0.169892,-0.091536,0.013273,1997,2
2,1997-03-01,-0.063839,-0.107597,0.156827,-0.103878,-0.078832,0.043007,0.050671,0.173173,-0.091504,0.012816,1997,3
3,1997-04-01,-0.065408,-0.110540,0.156606,-0.102309,-0.078543,0.044115,0.048243,0.173885,-0.092503,0.009471,1997,4
4,1997-05-01,-0.065689,-0.106693,0.155967,-0.103517,-0.079762,0.045164,0.049001,0.174296,-0.090993,0.012133,1997,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2014-08-01,-0.052493,-0.105543,0.153189,-0.065142,-0.041434,0.027570,0.067321,0.170376,-0.067194,0.016650,2014,8
212,2014-09-01,-0.053162,-0.102856,0.145749,-0.065079,-0.044546,0.032219,0.068743,0.169735,-0.062945,0.021990,2014,9
213,2014-10-01,-0.054174,-0.102440,0.147937,-0.064903,-0.043882,0.031681,0.067615,0.171407,-0.068079,0.020454,2014,10
214,2014-11-01,-0.056066,-0.100014,0.147666,-0.067999,-0.048929,0.034158,0.065755,0.170303,-0.068303,0.016019,2014,11
215,2014-12-01,-0.056269,-0.101391,0.147476,-0.065181,-0.046686,0.034508,0.066257,0.172767,-0.070648,0.014156,2014,12

In [18]:
train_firm_2018_temp

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19,month
0,ERTS,16721,75828,7372,3.0,11.0,36,1997,0.064718,1997-01-31,...,-0.007866,0.023190,-0.168285,-0.121665,-0.038322,-0.084682,-0.117417,-0.006333,0.107252,1
1,BMCS,14650,11976,7372,3.0,11.0,36,1997,0.048338,1997-01-31,...,-0.016959,0.025945,-0.175594,-0.120998,-0.043793,-0.091056,-0.118346,-0.005521,0.112488,1
2,LOW,6829,61399,5211,1.0,11.0,43,1997,-0.068632,1997-01-31,...,-0.014530,0.025004,-0.173039,-0.132915,-0.045645,-0.091474,-0.115696,-0.006687,0.123626,1
3,NKE,7906,57665,3021,1.0,11.0,10,1997,0.139583,1997-01-31,...,-0.023995,0.030466,-0.171475,-0.120554,-0.037044,-0.110117,-0.132952,-0.001920,0.108977,1
4,CPC,61404,82295,7500,1.0,11.0,33,1997,0.014925,1997-01-31,...,-0.034333,0.026528,-0.172744,-0.121261,-0.049424,-0.100359,-0.121147,0.000458,0.118068,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200964,NOC,7985,24766,3812,1.0,11.0,37,2014,0.045838,2014-12-31,...,-0.020363,0.029617,-0.184254,-0.114508,-0.045516,-0.087337,-0.126549,-0.008538,0.113358,12
200965,CVX,2991,14541,2911,1.0,11.0,30,2014,0.030403,2014-12-31,...,-0.031406,0.020202,-0.165850,-0.117160,-0.033731,-0.110053,-0.128346,0.000837,0.108359,12
200966,NOV,63892,84032,3533,1.0,11.0,21,2014,-0.015662,2014-12-31,...,-0.028163,0.029501,-0.187490,-0.113842,-0.049172,-0.094033,-0.127666,-0.006647,0.111515,12
200967,APO,184254,12591,6282,1.0,11.0,48,2014,-0.035188,2014-12-31,...,-0.034797,0.027056,-0.172068,-0.124870,-0.042095,-0.095095,-0.112806,-0.001466,0.122732,12
200968,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,-0.021195,0.020401,-0.178642,-0.124031,-0.047027,-0.089720,-0.111678,-0.008424,0.117021,12

## **데이터 저장**

In [19]:
## Save
output_file_path = os.path.join(base_path2, 'mergedData', '03_M2010_F2020')
os.makedirs(output_file_path, exist_ok=True)

train_2018.to_csv(os.path.join(output_file_path, 'train2018.csv'), index=False)
valid_2018.to_csv(os.path.join(output_file_path, 'valid2018.csv'), index=False)
test_2018.to_csv(os.path.join(output_file_path, 'test2018.csv'), index=False)

train_2019.to_csv(os.path.join(output_file_path, 'train2019.csv'), index=False)
valid_2019.to_csv(os.path.join(output_file_path, 'valid2019.csv'), index=False)
test_2019.to_csv(os.path.join(output_file_path, 'test2019.csv'), index=False)

train_2020.to_csv(os.path.join(output_file_path, 'train2020.csv'), index=False)
valid_2020.to_csv(os.path.join(output_file_path, 'valid2020.csv'), index=False)
test_2020.to_csv(os.path.join(output_file_path, 'test2020.csv'), index=False)

train_2021.to_csv(os.path.join(output_file_path, 'train2021.csv'), index=False)
valid_2021.to_csv(os.path.join(output_file_path, 'valid2021.csv'), index=False)
test_2021.to_csv(os.path.join(output_file_path, 'test2021.csv'), index=False)