- Macro HS : 50-10
- Firm HS : 20-20

## **설정**

In [1]:
## Google Drive Amount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
## Import libaries
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
## Setting
base_path1 = '/content/drive/MyDrive/CS/'
base_path2 = '/content/drive/MyDrive/CS2/'

## **데이터 불러오기**

### **Macro**

In [4]:
## Load the data
file_path = os.path.join(base_path2, 'hidden_states', 'CNN_BiLSTM_macro')

train_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_50_10_macro.csv'))
valid_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_50_10_macro.csv'))
test_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_50_10_macro.csv'))

train_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_50_10_macro.csv'))
valid_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_50_10_macro.csv'))
test_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_50_10_macro.csv'))

train_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_50_10_macro.csv'))
valid_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_50_10_macro.csv'))
test_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_50_10_macro.csv'))

train_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_50_10_macro.csv'))
valid_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_50_10_macro.csv'))
test_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_50_10_macro.csv'))

In [5]:
train_macro_2018

,sasdate,hs_10_0,hs_10_1,hs_10_2,hs_10_3,hs_10_4,hs_10_5,hs_10_6,hs_10_7,hs_10_8,hs_10_9
0,1997-01-01,-0.014042,-0.020660,0.047901,-0.090232,0.053093,-0.056258,0.084362,-0.070571,0.096853,-0.084651
1,1997-02-01,-0.013160,-0.020314,0.048569,-0.090147,0.053389,-0.051839,0.082565,-0.071331,0.097214,-0.083864
2,1997-03-01,-0.009516,-0.018641,0.046307,-0.093714,0.055353,-0.056025,0.081437,-0.069399,0.095558,-0.084183
3,1997-04-01,-0.014423,-0.016329,0.044970,-0.095621,0.059250,-0.058057,0.078214,-0.068048,0.097638,-0.082893
4,1997-05-01,-0.011683,-0.019519,0.047093,-0.095312,0.056417,-0.054228,0.080200,-0.070323,0.100891,-0.080539
...,...,...,...,...,...,...,...,...,...,...,...
211,2014-08-01,-0.004423,-0.012478,0.029862,-0.093173,0.069597,-0.063387,0.050775,-0.053635,0.080136,-0.063456
212,2014-09-01,0.000438,-0.012236,0.033392,-0.089242,0.065159,-0.058900,0.048607,-0.055379,0.080893,-0.061077
213,2014-10-01,-0.002093,-0.012765,0.036890,-0.088568,0.063657,-0.057164,0.051762,-0.055873,0.081819,-0.068293
214,2014-11-01,0.000178,-0.012611,0.032432,-0.088198,0.063619,-0.055588,0.046305,-0.053599,0.081158,-0.060485
215,2014-12-01,-0.002412,-0.012238,0.032329,-0.085807,0.061272,-0.063100,0.050245,-0.053626,0.079605,-0.063026

In [6]:
valid_macro_2018

,sasdate,hs_10_0,hs_10_1,hs_10_2,hs_10_3,hs_10_4,hs_10_5,hs_10_6,hs_10_7,hs_10_8,hs_10_9
0,2015-01-01,-0.000792,-0.011373,0.033894,-0.082567,0.061705,-0.058858,0.047009,-0.054908,0.076187,-0.066357
1,2015-02-01,-0.002180,-0.008056,0.032994,-0.083593,0.062517,-0.058893,0.049531,-0.056088,0.076888,-0.065154
2,2015-03-01,-0.002820,-0.005290,0.035772,-0.083707,0.062921,-0.055680,0.049639,-0.059150,0.078762,-0.065838
3,2015-04-01,-0.002949,-0.004903,0.033391,-0.085017,0.060006,-0.056153,0.048762,-0.056306,0.078900,-0.065330
4,2015-05-01,-0.001096,-0.005552,0.034876,-0.085297,0.060981,-0.058532,0.050313,-0.057430,0.076042,-0.067033
5,2015-06-01,-0.000778,-0.006366,0.037934,-0.079592,0.056463,-0.058948,0.051577,-0.060262,0.075532,-0.067239
6,2015-07-01,-0.004801,-0.005385,0.035740,-0.082895,0.058578,-0.058348,0.045422,-0.055714,0.077252,-0.062467
7,2015-08-01,0.002744,-0.007282,0.030879,-0.086092,0.056945,-0.062028,0.046852,-0.052955,0.075008,-0.059052
8,2015-09-01,0.001241,-0.005839,0.036691,-0.079932,0.051508,-0.051875,0.051844,-0.057592,0.077572,-0.064502
9,2015-10-01,0.002396,0.000023,0.034052,-0.086420,0.056501,-0.051302,0.048345,-0.052677,0.080995,-0.059461
10,2015-11-01,0.004654,0.000095,0.031890,-0.087068,0.056352,-0.055247,0.048598,-0.051681,0.077372,-0.056968
11,2015-12-01,0.000432,0.001208,0.034107,-0.083010,0.059146,-0.053577,0.046881,-0.055076,0.075115,-0.062595
12,2016-01-01,0.001112,0.001001,0.032774,-0.078744,0.057392,-0.063065,0.048283,-0.058706,0.079515,-0.061894
13,2016-02-01,-0.000632,-0.000050,0.033555,-0.078678,0.057592,-0.063114,0.048847,-0.059543,0.080264,-0.059337
14,2016-03-01,-0.001579,-0.000713,0.033166,-0.076260,0.052997,-0.065525,0.051151,-0.059885,0.082497,-0.057580
15,2016-04-01,-0.000422,0.005754,0.034997,-0.078873,0.059485,-0.066251,0.048693,-0.061092,0.085758,-0.052597
16,2016-05-01,-0.003900,0.003326,0.035555,-0.079326,0.054528,-0.065296,0.051703,-0.058516,0.087158,-0.055723
17,2016-06-01,-0.000048,0.004780,0.033242,-0.075588,0.058247,-0.067233,0.050078,-0.057519,0.082847,-0.054574
18,2016-07-01,-0.003046,0.007150,0.031579,-0.077334,0.059734,-0.071410,0.049060,-0.058066,0.085376,-0.055798
19,2016-08-01,-0.002494,0.004950,0.037040,-0.079824,0.060494,-0.061120,0.053664,-0.061427,0.082994,-0.057347
20,2016-09-01,-0.002719,0.002465,0.034049,-0.081120,0.061405,-0.060480,0.052724,-0.055970,0.083465,-0.059999
21,2016-10-01,-0.001242,0.000850,0.034805,-0.080523,0.062657,-0.063789,0.050274,-0.054495,0.083118,-0.059224
22,2016-11-01,-0.003140,-0.000074,0.038897,-0.080887,0.062700,-0.062124,0.050962,-0.056912,0.085090,-0.059011
23,2016-12-01,0.003787,-0.002329,0.036640,-0.073457,0.056171,-0.063952,0.053852,-0.060571,0.083912,-0.057819
24,2017-01-01,-0.001529,0.005601,0.036122,-0.078250,0.059841,-0.068988,0.049792,-0.056499,0.088742,-0.048561
25,2017-02-01,-0.001846,0.002716,0.034455,-0.080642,0.062396,-0.072026,0.049585,-0.057611,0.087122,-0.053494
26,2017-03-01,0.000498,0.002790,0.037326,-0.080328,0.065153,-0.068779,0.051344,-0.060608,0.086018,-0.054590
27,2017-04-01,-0.002262,0.003138,0.038805,-0.079387,0.060191,-0.066770,0.052362,-0.059785,0.094700,-0.052078
28,2017-05-01,-0.004420,0.002654,0.036426,-0.078823,0.060848,-0.067749,0.052744,-0.057591,0.092506,-0.049901
29,2017-06-01,-0.007147,0.002644,0.040236,-0.077784,0.060614,-0.066045,0.053126,-0.056761,0.090512,-0.055887
30,2017-07-01,-0.007633,-0.000513,0.042107,-0.080624,0.063351,-0.062100,0.056629,-0.057226,0.089068,-0.059321
31,2017-08-01,-0.001392,-0.000927,0.042823,-0.078814,0.060478,-0.058131,0.054881,-0.056201,0.088088,-0.058735
32,2017-09-01,-0.007202,-0.001991,0.043471,-0.080979,0.061990,-0.058784,0.055555,-0.053758,0.091256,-0.058274
33,2017-10-01,-0.007000,-0.001993,0.041247,-0.084208,0.063645,-0.059526,0.052320,-0.052413,0.093340,-0.056642
34,2017-11-01,-0.006033,0.000547,0.041454,-0.081709,0.060751,-0.058354,0.054930,-0.051080,0.091839,-0.056850
35,2017-12-01,-0.005175,0.001103,0.043536,-0.082385,0.060304,-0.058577,0.056211,-0.051413,0.092379,-0.059046

In [7]:
test_macro_2021

,sasdate,hs_10_0,hs_10_1,hs_10_2,hs_10_3,hs_10_4,hs_10_5,hs_10_6,hs_10_7,hs_10_8,hs_10_9
0,2021-01-01,0.021215,-0.034801,0.024929,-0.092572,0.103089,-0.047999,0.002998,-0.023717,0.016842,-0.102869
1,2021-02-01,0.014365,-0.047837,0.025956,-0.096688,0.096010,-0.050903,0.005278,-0.029615,0.031646,-0.103446
2,2021-03-01,0.013128,-0.052091,0.031124,-0.094751,0.101019,-0.054168,0.004130,-0.033583,0.037550,-0.111642
3,2021-04-01,0.008856,-0.053528,0.030434,-0.097287,0.098462,-0.052406,0.002983,-0.030571,0.041523,-0.113410
4,2021-05-01,0.006614,-0.048879,0.024122,-0.102906,0.098176,-0.055059,-0.003241,-0.026417,0.036875,-0.112871
5,2021-06-01,0.002694,-0.048097,0.029786,-0.104818,0.098090,-0.050813,0.001886,-0.030406,0.041096,-0.109928
6,2021-07-01,-0.001590,-0.049551,0.029794,-0.104705,0.101714,-0.050880,0.000315,-0.030081,0.037631,-0.111228
7,2021-08-01,-0.003914,-0.054234,0.032878,-0.105772,0.104568,-0.047727,0.000565,-0.029452,0.038397,-0.118905
8,2021-09-01,-0.000637,-0.054409,0.032265,-0.101940,0.107035,-0.046999,-0.004501,-0.028196,0.038615,-0.115720
9,2021-10-01,-0.007471,-0.058250,0.035303,-0.098196,0.109630,-0.046461,-0.004358,-0.028110,0.038117,-0.122283
10,2021-11-01,-0.009745,-0.059514,0.029993,-0.103820,0.110454,-0.046671,-0.010022,-0.021910,0.037107,-0.118127
11,2021-12-01,-0.009043,-0.058754,0.029691,-0.102264,0.116016,-0.048804,-0.010071,-0.021234,0.035773,-0.117376

### **Firm**

In [8]:
## Load the data
file_path = os.path.join(base_path1, 'hidden_states', 'CNNLSTM_Firm_simple')

train_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_20_20_Firm.csv'))

train_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_20_20_Firm.csv'))
valid_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_20_20_Firm.csv'))
test_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_20_20_Firm.csv'))

In [9]:
train_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,ERTS,16721,75828,7372,3.0,11.0,36,1997,0.064718,1997-01-31,...,0.028291,-0.007866,0.023190,-0.168285,-0.121665,-0.038322,-0.084682,-0.117417,-0.006333,0.107252
1,BMCS,14650,11976,7372,3.0,11.0,36,1997,0.048338,1997-01-31,...,0.032954,-0.016959,0.025945,-0.175594,-0.120998,-0.043793,-0.091056,-0.118346,-0.005521,0.112488
2,LOW,6829,61399,5211,1.0,11.0,43,1997,-0.068632,1997-01-31,...,0.035294,-0.014530,0.025004,-0.173039,-0.132915,-0.045645,-0.091474,-0.115696,-0.006687,0.123626
3,NKE,7906,57665,3021,1.0,11.0,10,1997,0.139583,1997-01-31,...,0.022729,-0.023995,0.030466,-0.171475,-0.120554,-0.037044,-0.110117,-0.132952,-0.001920,0.108977
4,CPC,61404,82295,7500,1.0,11.0,33,1997,0.014925,1997-01-31,...,0.027012,-0.034333,0.026528,-0.172744,-0.121261,-0.049424,-0.100359,-0.121147,0.000458,0.118068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200964,NOC,7985,24766,3812,1.0,11.0,37,2014,0.045838,2014-12-31,...,0.028322,-0.020363,0.029617,-0.184254,-0.114508,-0.045516,-0.087337,-0.126549,-0.008538,0.113358
200965,CVX,2991,14541,2911,1.0,11.0,30,2014,0.030403,2014-12-31,...,-0.004557,-0.031406,0.020202,-0.165850,-0.117160,-0.033731,-0.110053,-0.128346,0.000837,0.108359
200966,NOV,63892,84032,3533,1.0,11.0,21,2014,-0.015662,2014-12-31,...,0.024741,-0.028163,0.029501,-0.187490,-0.113842,-0.049172,-0.094033,-0.127666,-0.006647,0.111515
200967,APO,184254,12591,6282,1.0,11.0,48,2014,-0.035188,2014-12-31,...,0.027518,-0.034797,0.027056,-0.172068,-0.124870,-0.042095,-0.095095,-0.112806,-0.001466,0.122732
200968,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,0.037704,-0.021195,0.020401,-0.178642,-0.124031,-0.047027,-0.089720,-0.111678,-0.008424,0.117021

In [10]:
valid_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2015,-0.074988,2015-01-31,...,0.026567,-0.016915,0.025953,-0.171181,-0.112156,-0.039687,-0.104199,-0.127550,-0.007495,0.102085
1,LEN,6669,52708,1531,1.0,11.0,18,2015,0.003124,2015-01-31,...,0.016007,-0.024501,0.023155,-0.180788,-0.113822,-0.043913,-0.100784,-0.135893,-0.005865,0.109427
2,LH,14960,12062,8071,1.0,11.0,11,2015,0.063763,2015-01-31,...,0.035078,-0.022535,0.028517,-0.177842,-0.115206,-0.046598,-0.095281,-0.115647,-0.010728,0.109484
3,LII,122380,87034,3585,1.0,11.0,21,2015,0.034080,2015-01-31,...,0.034646,-0.019149,0.022177,-0.180713,-0.123819,-0.049908,-0.087230,-0.116596,-0.008228,0.117506
4,ATR,28176,79133,3089,1.0,11.0,15,2015,-0.051616,2015-01-31,...,0.035715,-0.022084,0.025698,-0.179924,-0.121552,-0.048855,-0.089112,-0.117722,-0.007429,0.116795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34686,NEU,4462,42550,2860,1.0,11.0,14,2017,-0.003445,2017-12-31,...,0.034292,-0.018306,0.023190,-0.178181,-0.124788,-0.044017,-0.091220,-0.116545,-0.007320,0.117605
34687,NEM,7881,21207,1040,1.0,11.0,27,2017,0.016356,2017-12-31,...,0.028763,-0.021891,0.021246,-0.181541,-0.114759,-0.044341,-0.097377,-0.129094,-0.005299,0.109074
34688,NEE,4517,24205,4911,1.0,11.0,31,2017,-0.011706,2017-12-31,...,0.019930,-0.027107,0.025571,-0.179420,-0.121367,-0.043505,-0.097075,-0.123316,-0.006829,0.116957
34689,NOC,7985,24766,3812,1.0,11.0,37,2017,0.001659,2017-12-31,...,0.029602,-0.019504,0.028004,-0.180424,-0.119011,-0.047249,-0.093908,-0.119810,-0.011278,0.110710
34690,ZTS,13721,13788,2834,1.0,11.0,13,2017,-0.003458,2017-12-31,...,0.035575,-0.011329,0.023760,-0.180566,-0.124087,-0.042748,-0.082984,-0.116031,-0.009348,0.114566

In [11]:
test_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2018,0.096461,2018-01-31,...,0.035436,-0.015706,0.028321,-0.176203,-0.114643,-0.045251,-0.098269,-0.114701,-0.012483,0.104588
1,LLL,110685,86021,3812,1.0,11.0,37,2018,0.073844,2018-01-31,...,0.031223,-0.022190,0.029893,-0.181655,-0.118415,-0.046082,-0.089001,-0.120674,-0.008757,0.115599
2,LLY,6730,50876,2834,1.0,11.0,13,2018,-0.035638,2018-01-31,...,0.027470,-0.013187,0.023839,-0.178150,-0.124271,-0.041893,-0.093218,-0.121877,-0.010802,0.112201
3,LM,6653,65330,6282,1.0,11.0,48,2018,0.015245,2018-01-31,...,0.040769,-0.020485,0.030661,-0.176477,-0.113864,-0.046428,-0.091919,-0.119390,-0.007562,0.110765
4,LMT,6774,21178,3760,1.0,11.0,26,2018,0.105280,2018-01-31,...,0.014493,-0.012252,0.025593,-0.172696,-0.124126,-0.033631,-0.101393,-0.129580,-0.011280,0.108928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11560,AKAM,125595,87299,7370,3.0,11.0,36,2018,-0.111564,2018-12-31,...,0.041080,-0.018627,0.022229,-0.177067,-0.121872,-0.050269,-0.094039,-0.105799,-0.011501,0.113171
11561,SLM,20430,66325,6141,3.0,11.0,45,2018,-0.190847,2018-12-31,...,0.031181,-0.029544,0.024388,-0.179225,-0.127731,-0.045825,-0.089269,-0.113244,-0.004208,0.123345
11562,FCX,14590,81774,1000,1.0,11.0,28,2018,-0.136516,2018-12-31,...,0.030963,-0.024622,0.018736,-0.177877,-0.128327,-0.045771,-0.094385,-0.114665,-0.007811,0.125633
11563,SNAP,30091,16595,7370,1.0,11.0,36,2018,-0.153610,2018-12-31,...,0.017286,-0.012426,0.017683,-0.163788,-0.107012,-0.030614,-0.083088,-0.121814,-0.018666,0.086257
11564,ZTS,13721,13788,2834,1.0,11.0,13,2018,-0.088740,2018-12-31,...,0.037183,-0.016096,0.023275,-0.179821,-0.123490,-0.048574,-0.093133,-0.112396,-0.012563,0.113149

## **병합**

In [12]:
def generate_year_month_forMacro(train, valid, test):
  ## Datetime 변환
  train['sasdate']=pd.to_datetime(train['sasdate'])
  valid['sasdate']=pd.to_datetime(valid['sasdate'])
  test['sasdate']=pd.to_datetime(test['sasdate'])

  ## Join할 year, month 변수 생성
  train['year'] = train['sasdate'].dt.year
  train['month'] = train['sasdate'].dt.month

  valid['year'] = valid['sasdate'].dt.year
  valid['month'] = valid['sasdate'].dt.month

  test['year'] = test['sasdate'].dt.year
  test['month'] = test['sasdate'].dt.month

  return(train, valid, test)

def generate_year_month_forFirm(train, valid, test):
  ## Datetime 변환
  train['date']=pd.to_datetime(train['date'])
  valid['date']=pd.to_datetime(valid['date'])
  test['date']=pd.to_datetime(test['date'])

  ## Join할 year, month 변수 생성
  train['year'] = train['date'].dt.year
  train['month'] = train['date'].dt.month

  valid['year'] = valid['date'].dt.year
  valid['month'] = valid['date'].dt.month

  test['year'] = test['date'].dt.year
  test['month'] = test['date'].dt.month

  return(train, valid, test)

In [13]:
train_macro_2018_temp, valid_macro_2018_temp, test_macro_2018_temp = generate_year_month_forMacro(train_macro_2018, valid_macro_2018, test_macro_2018)
train_macro_2019_temp, valid_macro_2019_temp, test_macro_2019_temp = generate_year_month_forMacro(train_macro_2019, valid_macro_2019, test_macro_2019)
train_macro_2020_temp, valid_macro_2020_temp, test_macro_2020_temp = generate_year_month_forMacro(train_macro_2020, valid_macro_2020, test_macro_2020)
train_macro_2021_temp, valid_macro_2021_temp, test_macro_2021_temp = generate_year_month_forMacro(train_macro_2021, valid_macro_2021, test_macro_2021)

train_firm_2018_temp, valid_firm_2018_temp, test_firm_2018_temp = generate_year_month_forFirm(train_firm_2018, valid_firm_2018, test_firm_2018)
train_firm_2019_temp, valid_firm_2019_temp, test_firm_2019_temp = generate_year_month_forFirm(train_firm_2019, valid_firm_2019, test_firm_2019)
train_firm_2020_temp, valid_firm_2020_temp, test_firm_2020_temp = generate_year_month_forFirm(train_firm_2020, valid_firm_2020, test_firm_2020)
train_firm_2021_temp, valid_firm_2021_temp, test_firm_2021_temp = generate_year_month_forFirm(train_firm_2021, valid_firm_2021, test_firm_2021)

In [14]:
train_2018 = pd.merge(train_firm_2018_temp, train_macro_2018_temp, on=['year', 'month'], how='left')
valid_2018 = pd.merge(valid_firm_2018_temp, valid_macro_2018_temp, on=['year', 'month'], how='left')
test_2018 = pd.merge(test_firm_2018_temp, test_macro_2018_temp, on=['year', 'month'], how='left')

train_2019 = pd.merge(train_firm_2019_temp, train_macro_2019_temp, on=['year', 'month'], how='left')
valid_2019 = pd.merge(valid_firm_2019_temp, valid_macro_2019_temp, on=['year', 'month'], how='left')
test_2019 = pd.merge(test_firm_2019_temp, test_macro_2019_temp, on=['year', 'month'], how='left')

train_2020 = pd.merge(train_firm_2020_temp, train_macro_2020_temp, on=['year', 'month'], how='left')
valid_2020 = pd.merge(valid_firm_2020_temp, valid_macro_2020_temp, on=['year', 'month'], how='left')
test_2020 = pd.merge(test_firm_2020_temp, test_macro_2020_temp, on=['year', 'month'], how='left')

train_2021 = pd.merge(train_firm_2021_temp, train_macro_2021_temp, on=['year', 'month'], how='left')
valid_2021 = pd.merge(valid_firm_2021_temp, valid_macro_2021_temp, on=['year', 'month'], how='left')
test_2021 = pd.merge(test_firm_2021_temp, test_macro_2021_temp, on=['year', 'month'], how='left')

In [15]:
train_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

In [16]:
print(sum(train_2018.isnull().sum()))
print(sum(test_2018.isnull().sum()))
print(sum(valid_2018.isnull().sum()))

print(sum(train_2019.isnull().sum()))
print(sum(test_2019.isnull().sum()))
print(sum(valid_2019.isnull().sum()))

print(sum(train_2020.isnull().sum()))
print(sum(test_2020.isnull().sum()))
print(sum(valid_2020.isnull().sum()))

print(sum(train_2021.isnull().sum()))
print(sum(test_2021.isnull().sum()))
print(sum(valid_2021.isnull().sum()))

0
0
0
0
0
0
0
0
0
0
0
0

In [17]:
train_macro_2018_temp

,sasdate,hs_10_0,hs_10_1,hs_10_2,hs_10_3,hs_10_4,hs_10_5,hs_10_6,hs_10_7,hs_10_8,hs_10_9,year,month
0,1997-01-01,-0.014042,-0.020660,0.047901,-0.090232,0.053093,-0.056258,0.084362,-0.070571,0.096853,-0.084651,1997,1
1,1997-02-01,-0.013160,-0.020314,0.048569,-0.090147,0.053389,-0.051839,0.082565,-0.071331,0.097214,-0.083864,1997,2
2,1997-03-01,-0.009516,-0.018641,0.046307,-0.093714,0.055353,-0.056025,0.081437,-0.069399,0.095558,-0.084183,1997,3
3,1997-04-01,-0.014423,-0.016329,0.044970,-0.095621,0.059250,-0.058057,0.078214,-0.068048,0.097638,-0.082893,1997,4
4,1997-05-01,-0.011683,-0.019519,0.047093,-0.095312,0.056417,-0.054228,0.080200,-0.070323,0.100891,-0.080539,1997,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2014-08-01,-0.004423,-0.012478,0.029862,-0.093173,0.069597,-0.063387,0.050775,-0.053635,0.080136,-0.063456,2014,8
212,2014-09-01,0.000438,-0.012236,0.033392,-0.089242,0.065159,-0.058900,0.048607,-0.055379,0.080893,-0.061077,2014,9
213,2014-10-01,-0.002093,-0.012765,0.036890,-0.088568,0.063657,-0.057164,0.051762,-0.055873,0.081819,-0.068293,2014,10
214,2014-11-01,0.000178,-0.012611,0.032432,-0.088198,0.063619,-0.055588,0.046305,-0.053599,0.081158,-0.060485,2014,11
215,2014-12-01,-0.002412,-0.012238,0.032329,-0.085807,0.061272,-0.063100,0.050245,-0.053626,0.079605,-0.063026,2014,12

In [18]:
train_firm_2018_temp

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19,month
0,ERTS,16721,75828,7372,3.0,11.0,36,1997,0.064718,1997-01-31,...,-0.007866,0.023190,-0.168285,-0.121665,-0.038322,-0.084682,-0.117417,-0.006333,0.107252,1
1,BMCS,14650,11976,7372,3.0,11.0,36,1997,0.048338,1997-01-31,...,-0.016959,0.025945,-0.175594,-0.120998,-0.043793,-0.091056,-0.118346,-0.005521,0.112488,1
2,LOW,6829,61399,5211,1.0,11.0,43,1997,-0.068632,1997-01-31,...,-0.014530,0.025004,-0.173039,-0.132915,-0.045645,-0.091474,-0.115696,-0.006687,0.123626,1
3,NKE,7906,57665,3021,1.0,11.0,10,1997,0.139583,1997-01-31,...,-0.023995,0.030466,-0.171475,-0.120554,-0.037044,-0.110117,-0.132952,-0.001920,0.108977,1
4,CPC,61404,82295,7500,1.0,11.0,33,1997,0.014925,1997-01-31,...,-0.034333,0.026528,-0.172744,-0.121261,-0.049424,-0.100359,-0.121147,0.000458,0.118068,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200964,NOC,7985,24766,3812,1.0,11.0,37,2014,0.045838,2014-12-31,...,-0.020363,0.029617,-0.184254,-0.114508,-0.045516,-0.087337,-0.126549,-0.008538,0.113358,12
200965,CVX,2991,14541,2911,1.0,11.0,30,2014,0.030403,2014-12-31,...,-0.031406,0.020202,-0.165850,-0.117160,-0.033731,-0.110053,-0.128346,0.000837,0.108359,12
200966,NOV,63892,84032,3533,1.0,11.0,21,2014,-0.015662,2014-12-31,...,-0.028163,0.029501,-0.187490,-0.113842,-0.049172,-0.094033,-0.127666,-0.006647,0.111515,12
200967,APO,184254,12591,6282,1.0,11.0,48,2014,-0.035188,2014-12-31,...,-0.034797,0.027056,-0.172068,-0.124870,-0.042095,-0.095095,-0.112806,-0.001466,0.122732,12
200968,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,-0.021195,0.020401,-0.178642,-0.124031,-0.047027,-0.089720,-0.111678,-0.008424,0.117021,12

## **데이터 저장**

In [19]:
## Save
output_file_path = os.path.join(base_path2, 'mergedData', '04_M5010_F2020')
os.makedirs(output_file_path, exist_ok=True)

train_2018.to_csv(os.path.join(output_file_path, 'train2018.csv'), index=False)
valid_2018.to_csv(os.path.join(output_file_path, 'valid2018.csv'), index=False)
test_2018.to_csv(os.path.join(output_file_path, 'test2018.csv'), index=False)

train_2019.to_csv(os.path.join(output_file_path, 'train2019.csv'), index=False)
valid_2019.to_csv(os.path.join(output_file_path, 'valid2019.csv'), index=False)
test_2019.to_csv(os.path.join(output_file_path, 'test2019.csv'), index=False)

train_2020.to_csv(os.path.join(output_file_path, 'train2020.csv'), index=False)
valid_2020.to_csv(os.path.join(output_file_path, 'valid2020.csv'), index=False)
test_2020.to_csv(os.path.join(output_file_path, 'test2020.csv'), index=False)

train_2021.to_csv(os.path.join(output_file_path, 'train2021.csv'), index=False)
valid_2021.to_csv(os.path.join(output_file_path, 'valid2021.csv'), index=False)
test_2021.to_csv(os.path.join(output_file_path, 'test2021.csv'), index=False)