- Macro HS : 50-20
- Firm HS : 50-20

## **설정**

In [1]:
## Google Drive Amount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
## Import libaries
import pandas as pd
import numpy as np

import os

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
## Setting
base_path1 = '/content/drive/MyDrive/CS/'
base_path2 = '/content/drive/MyDrive/CS2/'

## **데이터 불러오기**

### **Macro**

In [4]:
## Load the data
file_path = os.path.join(base_path2, 'hidden_states', 'CNN_BiLSTM_macro')

train_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_50_20_macro.csv'))

train_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_50_20_macro.csv'))

train_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_50_20_macro.csv'))

train_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_50_20_macro.csv'))
valid_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_50_20_macro.csv'))
test_macro_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_50_20_macro.csv'))

In [5]:
train_macro_2018

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,1997-01-01,0.057025,0.073278,-0.023173,0.032760,-0.005649,-0.122041,0.103139,0.055050,0.038524,...,0.104684,0.090711,-0.011463,-0.026317,-0.087267,-0.018037,0.059776,0.101717,0.046226,-0.029024
1,1997-02-01,0.059609,0.072197,-0.021979,0.029673,-0.007404,-0.121461,0.101316,0.055348,0.035753,...,0.104174,0.091537,-0.014347,-0.025927,-0.089106,-0.019119,0.059793,0.104475,0.044338,-0.025448
2,1997-03-01,0.061302,0.071278,-0.028745,0.028745,-0.003115,-0.119806,0.099618,0.056171,0.040603,...,0.103897,0.088299,-0.006713,-0.023516,-0.089528,-0.016514,0.059583,0.102022,0.046775,-0.024236
3,1997-04-01,0.064227,0.069702,-0.026327,0.027499,-0.002711,-0.116570,0.096448,0.057557,0.042620,...,0.106125,0.092319,-0.010705,-0.021355,-0.089771,-0.017929,0.058872,0.100272,0.045227,-0.025625
4,1997-05-01,0.065488,0.069264,-0.031743,0.025974,-0.004273,-0.122828,0.094429,0.056245,0.040260,...,0.104683,0.092288,-0.011321,-0.027932,-0.092314,-0.018525,0.056781,0.100412,0.043646,-0.022361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2014-08-01,0.064902,0.036789,-0.036205,0.000865,0.006038,-0.104647,0.091402,0.056038,0.061092,...,0.119537,0.096162,-0.014210,-0.042632,-0.075872,-0.017735,0.058992,0.093128,0.034089,-0.011067
212,2014-09-01,0.071942,0.035491,-0.050250,-0.002824,0.012055,-0.113074,0.086959,0.058376,0.061936,...,0.114767,0.084929,-0.009459,-0.040707,-0.081480,-0.011195,0.060961,0.094968,0.035116,-0.013781
213,2014-10-01,0.068654,0.037076,-0.043506,-0.004941,0.014544,-0.107489,0.088078,0.057654,0.061889,...,0.113304,0.089231,-0.006295,-0.039347,-0.079372,-0.015617,0.057744,0.093251,0.033785,-0.009983
214,2014-11-01,0.071625,0.037593,-0.046569,-0.003718,0.018639,-0.104580,0.087210,0.060435,0.062635,...,0.117633,0.089669,-0.006299,-0.043490,-0.081938,-0.015995,0.058070,0.097214,0.030247,-0.010949
215,2014-12-01,0.064303,0.032635,-0.050737,0.003208,0.015823,-0.110551,0.089495,0.059351,0.062480,...,0.114963,0.090787,-0.008380,-0.043360,-0.079457,-0.015142,0.057855,0.091263,0.027930,-0.014102

In [6]:
valid_macro_2018

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,2015-01-01,0.066421,0.040163,-0.049433,-0.007746,0.015873,-0.105562,0.087504,0.058376,0.066111,...,0.118989,0.088005,0.002645,-0.041315,-0.084206,-0.011524,0.062228,0.091472,0.029399,-0.008369
1,2015-02-01,0.066489,0.039450,-0.046982,-0.006430,0.016229,-0.108174,0.090572,0.060946,0.063729,...,0.118755,0.087482,0.005489,-0.040669,-0.085171,-0.012893,0.063541,0.090824,0.027969,-0.008333
2,2015-03-01,0.062622,0.042077,-0.042074,-0.005115,0.012100,-0.106587,0.087609,0.063729,0.064432,...,0.118667,0.091215,0.005503,-0.038283,-0.085659,-0.011621,0.063823,0.089030,0.024962,-0.007402
3,2015-04-01,0.063094,0.043669,-0.044642,-0.005138,0.014055,-0.106225,0.088094,0.063411,0.065264,...,0.119437,0.092161,0.009481,-0.039554,-0.088764,-0.012131,0.061670,0.092181,0.025697,-0.009447
4,2015-05-01,0.062034,0.040989,-0.046528,-0.002614,0.016635,-0.107936,0.087647,0.062600,0.062834,...,0.117595,0.090594,0.013804,-0.037928,-0.090043,-0.013636,0.063834,0.094006,0.025953,-0.010061
5,2015-06-01,0.059070,0.041333,-0.048320,0.000439,0.017314,-0.112714,0.090780,0.062654,0.058729,...,0.118993,0.087740,0.012288,-0.039651,-0.089314,-0.009238,0.064553,0.091065,0.022437,-0.008190
6,2015-07-01,0.064713,0.043348,-0.054920,-0.000624,0.015716,-0.110221,0.090411,0.062073,0.066761,...,0.120392,0.086977,0.013191,-0.040301,-0.086441,-0.008354,0.062556,0.094473,0.030379,-0.014270
7,2015-08-01,0.060742,0.045986,-0.053856,0.003902,0.016437,-0.111715,0.092636,0.060470,0.061773,...,0.120889,0.082212,0.011465,-0.044369,-0.090916,-0.012777,0.063208,0.098082,0.029136,-0.021949
8,2015-09-01,0.053696,0.045610,-0.047439,0.006127,0.015864,-0.112251,0.104239,0.060695,0.062496,...,0.116680,0.074423,0.022673,-0.038714,-0.088810,-0.011398,0.063355,0.100763,0.030536,-0.017763
9,2015-10-01,0.062443,0.041529,-0.050649,0.001650,0.018796,-0.103903,0.102892,0.066765,0.067969,...,0.121594,0.073266,0.028022,-0.040606,-0.090386,-0.015337,0.059427,0.105115,0.034267,-0.016691
10,2015-11-01,0.062957,0.037738,-0.052660,0.004626,0.014089,-0.109417,0.101212,0.066471,0.062008,...,0.121667,0.077717,0.020025,-0.042848,-0.090345,-0.015385,0.062376,0.101977,0.027272,-0.017382
11,2015-12-01,0.060610,0.041467,-0.050818,0.005818,0.016489,-0.113509,0.094061,0.065889,0.063098,...,0.116870,0.081274,0.022257,-0.037054,-0.092849,-0.008079,0.067733,0.093617,0.024323,-0.010353
12,2016-01-01,0.060142,0.040745,-0.048897,0.004229,0.022164,-0.109355,0.095731,0.066443,0.061817,...,0.120043,0.082399,0.022952,-0.038807,-0.093004,-0.011189,0.064465,0.096443,0.025329,-0.008459
13,2016-02-01,0.058326,0.044904,-0.046931,0.003212,0.019131,-0.112000,0.095414,0.063912,0.061099,...,0.121676,0.083246,0.020933,-0.038360,-0.090681,-0.010580,0.066155,0.095170,0.028092,-0.011695
14,2016-03-01,0.053693,0.045309,-0.050745,0.001753,0.026074,-0.113677,0.098698,0.064267,0.060677,...,0.123842,0.082463,0.029330,-0.041749,-0.095821,-0.013475,0.065251,0.098209,0.029304,-0.009743
15,2016-04-01,0.058511,0.040944,-0.051853,0.005316,0.026596,-0.110856,0.096584,0.067728,0.065365,...,0.124513,0.081637,0.033423,-0.039290,-0.095519,-0.010333,0.067070,0.099666,0.029512,-0.010991
16,2016-05-01,0.053874,0.046980,-0.049994,0.002623,0.022325,-0.110712,0.097501,0.064231,0.066422,...,0.123782,0.084970,0.031193,-0.040523,-0.097393,-0.009581,0.068513,0.099600,0.027557,-0.010643
17,2016-06-01,0.053465,0.043473,-0.053655,0.008524,0.025219,-0.116668,0.097083,0.065148,0.063147,...,0.123219,0.079226,0.037243,-0.037049,-0.097088,-0.008157,0.070755,0.098737,0.030519,-0.009649
18,2016-07-01,0.057299,0.043216,-0.051441,0.006730,0.026036,-0.111474,0.095570,0.069325,0.067663,...,0.123391,0.080208,0.040206,-0.037484,-0.097053,-0.008748,0.068135,0.100369,0.034736,-0.010348
19,2016-08-01,0.054907,0.042119,-0.047234,0.005918,0.022761,-0.113455,0.099726,0.068576,0.066309,...,0.119682,0.079474,0.034598,-0.037192,-0.095429,-0.009693,0.071281,0.099968,0.028599,-0.012762
20,2016-09-01,0.053410,0.042726,-0.048069,0.007485,0.021567,-0.117303,0.098152,0.066480,0.067727,...,0.119399,0.081852,0.035665,-0.041484,-0.099265,-0.012382,0.066506,0.094349,0.028771,-0.012141
21,2016-10-01,0.057488,0.042109,-0.048814,0.004716,0.022544,-0.113422,0.097894,0.064753,0.067657,...,0.120107,0.080312,0.034943,-0.039495,-0.096012,-0.011504,0.067578,0.096024,0.029420,-0.009429
22,2016-11-01,0.057622,0.041203,-0.052084,0.005841,0.021978,-0.115908,0.097499,0.062631,0.069481,...,0.116413,0.078341,0.033508,-0.037269,-0.093194,-0.009288,0.069487,0.097181,0.030254,-0.015332
23,2016-12-01,0.048829,0.041901,-0.047784,0.011742,0.022190,-0.118285,0.099124,0.064643,0.061498,...,0.116844,0.076214,0.032248,-0.040572,-0.097371,-0.008942,0.068988,0.097246,0.023273,-0.012988
24,2017-01-01,0.054945,0.040344,-0.054256,0.012304,0.024496,-0.115729,0.098748,0.065630,0.068681,...,0.123255,0.077237,0.036731,-0.039934,-0.095051,-0.008796,0.069169,0.101122,0.030801,-0.014783
25,2017-02-01,0.054180,0.040317,-0.052318,0.009375,0.021934,-0.114644,0.095154,0.063079,0.066433,...,0.121445,0.080811,0.035102,-0.040385,-0.096420,-0.011078,0.069549,0.098496,0.029751,-0.016343
26,2017-03-01,0.058400,0.038023,-0.050918,0.008524,0.027842,-0.114873,0.097334,0.065487,0.065244,...,0.119075,0.077407,0.036581,-0.039756,-0.098412,-0.014685,0.069649,0.099815,0.030693,-0.016294
27,2017-04-01,0.054174,0.044772,-0.048443,0.001770,0.020183,-0.115372,0.094007,0.067287,0.066710,...,0.119884,0.080170,0.035456,-0.038114,-0.096943,-0.007952,0.067157,0.098028,0.032132,-0.011544
28,2017-05-01,0.050639,0.048173,-0.047377,0.003817,0.019998,-0.115704,0.093557,0.065598,0.066343,...,0.124348,0.083224,0.033017,-0.039435,-0.096708,-0.009700,0.067560,0.099139,0.030869,-0.013988
29,2017-06-01,0.054795,0.045073,-0.051221,0.003069,0.024800,-0.117545,0.094997,0.068576,0.064710,...,0.119509,0.082377,0.036850,-0.035920,-0.096959,-0.012175,0.069990,0.099718,0.033661,-0.013785
30,2017-07-01,0.053726,0.045732,-0.047444,-0.002393,0.023888,-0.112623,0.098746,0.065930,0.067660,...,0.119764,0.084021,0.035710,-0.036871,-0.094664,-0.014736,0.067541,0.099028,0.033712,-0.011936
31,2017-08-01,0.055903,0.043658,-0.052961,-0.002423,0.026569,-0.116705,0.098099,0.064006,0.068005,...,0.115645,0.076820,0.037139,-0.036525,-0.097020,-0.010899,0.066428,0.097993,0.030477,-0.012581
32,2017-09-01,0.054272,0.047758,-0.052511,-0.004536,0.024991,-0.114352,0.097063,0.064379,0.073940,...,0.117305,0.080540,0.037882,-0.037329,-0.094288,-0.011205,0.063945,0.097163,0.033715,-0.011116
33,2017-10-01,0.057131,0.050163,-0.050439,-0.005815,0.022059,-0.114108,0.094729,0.063732,0.073094,...,0.117835,0.082864,0.034304,-0.035579,-0.094493,-0.011096,0.065540,0.098076,0.031321,-0.013933
34,2017-11-01,0.054312,0.046106,-0.052228,-0.000248,0.023383,-0.117015,0.096386,0.067546,0.070871,...,0.114558,0.082118,0.035571,-0.033866,-0.094748,-0.012571,0.064536,0.099834,0.031381,-0.015972
35,2017-12-01,0.055883,0.050109,-0.053023,-0.002753,0.027257,-0.115321,0.096043,0.065168,0.071955,...,0.116345,0.079749,0.040418,-0.034378,-0.096501,-0.011240,0.062958,0.100605,0.034063,-0.010877

In [7]:
test_macro_2021

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,2021-01-01,0.109897,0.056114,-0.044659,-0.018463,-0.011557,-0.109528,0.040271,0.063834,0.022762,...,0.104388,0.111266,-0.008591,-0.040719,-0.094524,-0.092295,0.088187,0.084558,0.038406,-0.030323
1,2021-02-01,0.109950,0.056059,-0.047310,-0.027038,-0.009584,-0.106802,0.046170,0.053179,0.026228,...,0.102400,0.111156,-0.019888,-0.042575,-0.089871,-0.089809,0.080290,0.085770,0.039256,-0.026453
2,2021-03-01,0.112705,0.050096,-0.047976,-0.029242,-0.007812,-0.109045,0.048902,0.046188,0.026042,...,0.096939,0.111766,-0.021953,-0.042797,-0.090308,-0.087169,0.081397,0.077962,0.033630,-0.030359
3,2021-04-01,0.113215,0.055440,-0.050003,-0.035865,-0.007489,-0.109166,0.044718,0.042611,0.031846,...,0.099106,0.118762,-0.017947,-0.050951,-0.092456,-0.089750,0.074458,0.075029,0.032040,-0.021078
4,2021-05-01,0.111300,0.053830,-0.047696,-0.034752,-0.011509,-0.103146,0.045731,0.043810,0.032698,...,0.099727,0.122093,-0.019950,-0.046082,-0.090423,-0.092116,0.074833,0.075620,0.033246,-0.026875
5,2021-06-01,0.113739,0.056623,-0.048266,-0.028451,-0.012512,-0.112198,0.044549,0.041816,0.034602,...,0.100427,0.122473,-0.017688,-0.054478,-0.091389,-0.094025,0.075258,0.074572,0.032665,-0.025934
6,2021-07-01,0.113741,0.054086,-0.049887,-0.028429,-0.009543,-0.115679,0.047068,0.040544,0.034958,...,0.098424,0.124695,-0.017522,-0.053072,-0.088572,-0.092764,0.078550,0.071212,0.034190,-0.025075
7,2021-08-01,0.117316,0.052945,-0.052081,-0.032218,-0.003191,-0.118910,0.052374,0.033302,0.037974,...,0.093633,0.122118,-0.014407,-0.056458,-0.090350,-0.098470,0.080535,0.070456,0.034694,-0.023536
8,2021-09-01,0.118124,0.049056,-0.052405,-0.031681,-0.006887,-0.121320,0.052455,0.030191,0.036362,...,0.092329,0.120279,-0.014736,-0.056957,-0.088709,-0.099588,0.081336,0.066734,0.028664,-0.024713
9,2021-10-01,0.114259,0.051079,-0.048401,-0.038020,-0.008158,-0.117075,0.055637,0.027294,0.042738,...,0.094602,0.123719,-0.013468,-0.058974,-0.084382,-0.100731,0.080822,0.066092,0.031414,-0.025176
10,2021-11-01,0.110830,0.053586,-0.046186,-0.037295,-0.012751,-0.121666,0.054090,0.020287,0.043810,...,0.093775,0.128204,-0.015677,-0.061660,-0.083591,-0.102620,0.082929,0.065801,0.029860,-0.022398
11,2021-12-01,0.110142,0.051520,-0.045543,-0.033630,-0.010937,-0.118940,0.054320,0.022552,0.045630,...,0.094027,0.127289,-0.011331,-0.059699,-0.082731,-0.102076,0.084136,0.065591,0.030753,-0.019989

### **Firm**

In [8]:
## Load the data
file_path = os.path.join(base_path1, 'hidden_states', 'CNNLSTM_Firm_simple')

train_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_train_50_20_Firm.csv'))
valid_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_valid_50_20_Firm.csv'))
test_firm_2018 = pd.read_csv(os.path.join(file_path, 'Test_2018', 'hidden_states_test_50_20_Firm.csv'))

train_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_train_50_20_Firm.csv'))
valid_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_valid_50_20_Firm.csv'))
test_firm_2019 = pd.read_csv(os.path.join(file_path, 'Test_2019', 'hidden_states_test_50_20_Firm.csv'))

train_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_train_50_20_Firm.csv'))
valid_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_valid_50_20_Firm.csv'))
test_firm_2020 = pd.read_csv(os.path.join(file_path, 'Test_2020', 'hidden_states_test_50_20_Firm.csv'))

train_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_train_50_20_Firm.csv'))
valid_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_valid_50_20_Firm.csv'))
test_firm_2021 = pd.read_csv(os.path.join(file_path, 'Test_2021', 'hidden_states_test_50_20_Firm.csv'))

In [9]:
train_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,ERTS,16721,75828,7372,3.0,11.0,36,1997,0.064718,1997-01-31,...,0.116428,0.073095,0.012811,-0.021340,-0.091850,0.001624,0.083273,0.097302,0.020908,-0.004974
1,BMCS,14650,11976,7372,3.0,11.0,36,1997,0.048338,1997-01-31,...,0.123196,0.079243,0.016592,-0.025942,-0.091290,0.005750,0.088067,0.102095,0.021969,-0.004713
2,LOW,6829,61399,5211,1.0,11.0,43,1997,-0.068632,1997-01-31,...,0.121381,0.082286,0.012418,-0.018880,-0.087804,0.006796,0.087420,0.095943,0.014748,-0.007162
3,NKE,7906,57665,3021,1.0,11.0,10,1997,0.139583,1997-01-31,...,0.124629,0.082985,0.020682,-0.033000,-0.086920,-0.008532,0.082152,0.096230,0.021234,0.003915
4,CPC,61404,82295,7500,1.0,11.0,33,1997,0.014925,1997-01-31,...,0.122180,0.081996,0.032252,-0.025587,-0.091589,-0.000745,0.086854,0.092682,0.020225,0.002370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200964,NOC,7985,24766,3812,1.0,11.0,37,2014,0.045838,2014-12-31,...,0.120699,0.080041,0.013006,-0.021230,-0.088243,0.007252,0.078170,0.084771,0.015597,0.008715
200965,CVX,2991,14541,2911,1.0,11.0,30,2014,0.030403,2014-12-31,...,0.124666,0.071782,0.004970,-0.032172,-0.095391,0.016860,0.078163,0.071052,0.015788,-0.005237
200966,NOV,63892,84032,3533,1.0,11.0,21,2014,-0.015662,2014-12-31,...,0.123807,0.076181,0.016469,-0.031374,-0.094377,0.005681,0.077192,0.069058,0.012797,0.016623
200967,APO,184254,12591,6282,1.0,11.0,48,2014,-0.035188,2014-12-31,...,0.117641,0.087045,0.027390,-0.029939,-0.107373,-0.012164,0.069386,0.071665,0.021660,0.016057
200968,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,0.122629,0.078946,0.017741,-0.020436,-0.089969,-0.002365,0.079082,0.093672,0.021937,0.001318

In [10]:
valid_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2015,-0.074988,2015-01-31,...,0.117301,0.076872,0.024905,-0.032568,-0.090976,-0.016603,0.078858,0.090034,0.017534,0.011079
1,LEN,6669,52708,1531,1.0,11.0,18,2015,0.003124,2015-01-31,...,0.124122,0.073986,0.021765,-0.033245,-0.091202,-0.008626,0.078048,0.092337,0.022267,0.011245
2,LH,14960,12062,8071,1.0,11.0,11,2015,0.063763,2015-01-31,...,0.121756,0.081857,0.017707,-0.021134,-0.088969,-0.002483,0.074401,0.090228,0.017947,0.003238
3,LII,122380,87034,3585,1.0,11.0,21,2015,0.034080,2015-01-31,...,0.123939,0.076691,0.015267,-0.020091,-0.086765,0.006374,0.077301,0.095003,0.022755,0.005473
4,ATR,28176,79133,3089,1.0,11.0,15,2015,-0.051616,2015-01-31,...,0.122186,0.082920,0.016937,-0.023126,-0.088404,-0.000400,0.077677,0.090290,0.018249,0.007016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34686,NEU,4462,42550,2860,1.0,11.0,14,2017,-0.003445,2017-12-31,...,0.123625,0.080176,0.013915,-0.021105,-0.087109,-0.000643,0.075058,0.095712,0.021624,0.007596
34687,NEM,7881,21207,1040,1.0,11.0,27,2017,0.016356,2017-12-31,...,0.125470,0.078318,0.022485,-0.036391,-0.089296,-0.012815,0.083398,0.090456,0.019106,0.012870
34688,NEE,4517,24205,4911,1.0,11.0,31,2017,-0.011706,2017-12-31,...,0.121461,0.077667,0.007974,-0.033055,-0.092472,0.002480,0.074727,0.079074,0.019684,0.009042
34689,NOC,7985,24766,3812,1.0,11.0,37,2017,0.001659,2017-12-31,...,0.123063,0.079236,0.012515,-0.024499,-0.091278,0.003174,0.078138,0.079546,0.014765,0.007601
34690,ZTS,13721,13788,2834,1.0,11.0,13,2017,-0.003458,2017-12-31,...,0.124584,0.076023,0.016507,-0.023419,-0.089568,-0.002790,0.077997,0.093190,0.023414,0.005923

In [11]:
test_firm_2018

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_10,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19
0,A,126554,87432,3826,1.0,11.0,38,2018,0.096461,2018-01-31,...,0.120991,0.074588,0.017588,-0.025228,-0.087352,-0.005701,0.075504,0.092061,0.021326,0.008838
1,LLL,110685,86021,3812,1.0,11.0,37,2018,0.073844,2018-01-31,...,0.123055,0.082227,0.016219,-0.024039,-0.089514,-0.000619,0.075878,0.087605,0.017317,0.008312
2,LLY,6730,50876,2834,1.0,11.0,13,2018,-0.035638,2018-01-31,...,0.122766,0.080117,0.012764,-0.026626,-0.090879,0.001740,0.079262,0.081556,0.017926,0.001202
3,LM,6653,65330,6282,1.0,11.0,48,2018,0.015245,2018-01-31,...,0.118360,0.079722,0.026915,-0.031248,-0.094680,-0.001601,0.074522,0.080908,0.014145,0.014048
4,LMT,6774,21178,3760,1.0,11.0,26,2018,0.105280,2018-01-31,...,0.118183,0.069790,0.012852,-0.025477,-0.086664,0.003833,0.078628,0.077147,0.017101,0.006082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11560,AKAM,125595,87299,7370,3.0,11.0,36,2018,-0.111564,2018-12-31,...,0.119437,0.076649,0.017595,-0.022686,-0.091917,0.007685,0.073025,0.085371,0.015555,0.010768
11561,SLM,20430,66325,6141,3.0,11.0,45,2018,-0.190847,2018-12-31,...,0.122671,0.081380,0.020280,-0.022499,-0.088654,0.005393,0.079676,0.090683,0.018163,0.011596
11562,FCX,14590,81774,1000,1.0,11.0,28,2018,-0.136516,2018-12-31,...,0.125329,0.076734,0.017015,-0.028929,-0.090404,0.005670,0.077042,0.085868,0.018454,0.014818
11563,SNAP,30091,16595,7370,1.0,11.0,36,2018,-0.153610,2018-12-31,...,0.115880,0.075843,0.026687,-0.035926,-0.098569,-0.017710,0.082827,0.081666,0.019385,0.002400
11564,ZTS,13721,13788,2834,1.0,11.0,13,2018,-0.088740,2018-12-31,...,0.125494,0.075369,0.012636,-0.022597,-0.087810,-0.001853,0.075650,0.091100,0.022905,0.007465

## **병합**

In [12]:
def generate_year_month_forMacro(train, valid, test):
  ## Datetime 변환
  train['sasdate']=pd.to_datetime(train['sasdate'])
  valid['sasdate']=pd.to_datetime(valid['sasdate'])
  test['sasdate']=pd.to_datetime(test['sasdate'])

  ## Join할 year, month 변수 생성
  train['year'] = train['sasdate'].dt.year
  train['month'] = train['sasdate'].dt.month

  valid['year'] = valid['sasdate'].dt.year
  valid['month'] = valid['sasdate'].dt.month

  test['year'] = test['sasdate'].dt.year
  test['month'] = test['sasdate'].dt.month

  return(train, valid, test)

def generate_year_month_forFirm(train, valid, test):
  ## Datetime 변환
  train['date']=pd.to_datetime(train['date'])
  valid['date']=pd.to_datetime(valid['date'])
  test['date']=pd.to_datetime(test['date'])

  ## Join할 year, month 변수 생성
  train['year'] = train['date'].dt.year
  train['month'] = train['date'].dt.month

  valid['year'] = valid['date'].dt.year
  valid['month'] = valid['date'].dt.month

  test['year'] = test['date'].dt.year
  test['month'] = test['date'].dt.month

  return(train, valid, test)

In [13]:
train_macro_2018_temp, valid_macro_2018_temp, test_macro_2018_temp = generate_year_month_forMacro(train_macro_2018, valid_macro_2018, test_macro_2018)
train_macro_2019_temp, valid_macro_2019_temp, test_macro_2019_temp = generate_year_month_forMacro(train_macro_2019, valid_macro_2019, test_macro_2019)
train_macro_2020_temp, valid_macro_2020_temp, test_macro_2020_temp = generate_year_month_forMacro(train_macro_2020, valid_macro_2020, test_macro_2020)
train_macro_2021_temp, valid_macro_2021_temp, test_macro_2021_temp = generate_year_month_forMacro(train_macro_2021, valid_macro_2021, test_macro_2021)

train_firm_2018_temp, valid_firm_2018_temp, test_firm_2018_temp = generate_year_month_forFirm(train_firm_2018, valid_firm_2018, test_firm_2018)
train_firm_2019_temp, valid_firm_2019_temp, test_firm_2019_temp = generate_year_month_forFirm(train_firm_2019, valid_firm_2019, test_firm_2019)
train_firm_2020_temp, valid_firm_2020_temp, test_firm_2020_temp = generate_year_month_forFirm(train_firm_2020, valid_firm_2020, test_firm_2020)
train_firm_2021_temp, valid_firm_2021_temp, test_firm_2021_temp = generate_year_month_forFirm(train_firm_2021, valid_firm_2021, test_firm_2021)

In [14]:
train_2018 = pd.merge(train_firm_2018_temp, train_macro_2018_temp, on=['year', 'month'], how='left')
valid_2018 = pd.merge(valid_firm_2018_temp, valid_macro_2018_temp, on=['year', 'month'], how='left')
test_2018 = pd.merge(test_firm_2018_temp, test_macro_2018_temp, on=['year', 'month'], how='left')

train_2019 = pd.merge(train_firm_2019_temp, train_macro_2019_temp, on=['year', 'month'], how='left')
valid_2019 = pd.merge(valid_firm_2019_temp, valid_macro_2019_temp, on=['year', 'month'], how='left')
test_2019 = pd.merge(test_firm_2019_temp, test_macro_2019_temp, on=['year', 'month'], how='left')

train_2020 = pd.merge(train_firm_2020_temp, train_macro_2020_temp, on=['year', 'month'], how='left')
valid_2020 = pd.merge(valid_firm_2020_temp, valid_macro_2020_temp, on=['year', 'month'], how='left')
test_2020 = pd.merge(test_firm_2020_temp, test_macro_2020_temp, on=['year', 'month'], how='left')

train_2021 = pd.merge(train_firm_2021_temp, train_macro_2021_temp, on=['year', 'month'], how='left')
valid_2021 = pd.merge(valid_firm_2021_temp, valid_macro_2021_temp, on=['year', 'month'], how='left')
test_2021 = pd.merge(test_firm_2021_temp, test_macro_2021_temp, on=['year', 'month'], how='left')

In [15]:
train_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2018.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2019.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2020.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

train_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
valid_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)
test_2021.drop(['year', 'month', 'sasdate'], axis=1, inplace=True)

In [16]:
print(sum(train_2018.isnull().sum()))
print(sum(test_2018.isnull().sum()))
print(sum(valid_2018.isnull().sum()))

print(sum(train_2019.isnull().sum()))
print(sum(test_2019.isnull().sum()))
print(sum(valid_2019.isnull().sum()))

print(sum(train_2020.isnull().sum()))
print(sum(test_2020.isnull().sum()))
print(sum(valid_2020.isnull().sum()))

print(sum(train_2021.isnull().sum()))
print(sum(test_2021.isnull().sum()))
print(sum(valid_2021.isnull().sum()))

0
0
0
0
0
0
0
0
0
0
0
0

In [17]:
train_macro_2018_temp

,sasdate,hs_20_0,hs_20_1,hs_20_2,hs_20_3,hs_20_4,hs_20_5,hs_20_6,hs_20_7,hs_20_8,...,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19,year,month
0,1997-01-01,0.057025,0.073278,-0.023173,0.032760,-0.005649,-0.122041,0.103139,0.055050,0.038524,...,-0.011463,-0.026317,-0.087267,-0.018037,0.059776,0.101717,0.046226,-0.029024,1997,1
1,1997-02-01,0.059609,0.072197,-0.021979,0.029673,-0.007404,-0.121461,0.101316,0.055348,0.035753,...,-0.014347,-0.025927,-0.089106,-0.019119,0.059793,0.104475,0.044338,-0.025448,1997,2
2,1997-03-01,0.061302,0.071278,-0.028745,0.028745,-0.003115,-0.119806,0.099618,0.056171,0.040603,...,-0.006713,-0.023516,-0.089528,-0.016514,0.059583,0.102022,0.046775,-0.024236,1997,3
3,1997-04-01,0.064227,0.069702,-0.026327,0.027499,-0.002711,-0.116570,0.096448,0.057557,0.042620,...,-0.010705,-0.021355,-0.089771,-0.017929,0.058872,0.100272,0.045227,-0.025625,1997,4
4,1997-05-01,0.065488,0.069264,-0.031743,0.025974,-0.004273,-0.122828,0.094429,0.056245,0.040260,...,-0.011321,-0.027932,-0.092314,-0.018525,0.056781,0.100412,0.043646,-0.022361,1997,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2014-08-01,0.064902,0.036789,-0.036205,0.000865,0.006038,-0.104647,0.091402,0.056038,0.061092,...,-0.014210,-0.042632,-0.075872,-0.017735,0.058992,0.093128,0.034089,-0.011067,2014,8
212,2014-09-01,0.071942,0.035491,-0.050250,-0.002824,0.012055,-0.113074,0.086959,0.058376,0.061936,...,-0.009459,-0.040707,-0.081480,-0.011195,0.060961,0.094968,0.035116,-0.013781,2014,9
213,2014-10-01,0.068654,0.037076,-0.043506,-0.004941,0.014544,-0.107489,0.088078,0.057654,0.061889,...,-0.006295,-0.039347,-0.079372,-0.015617,0.057744,0.093251,0.033785,-0.009983,2014,10
214,2014-11-01,0.071625,0.037593,-0.046569,-0.003718,0.018639,-0.104580,0.087210,0.060435,0.062635,...,-0.006299,-0.043490,-0.081938,-0.015995,0.058070,0.097214,0.030247,-0.010949,2014,11
215,2014-12-01,0.064303,0.032635,-0.050737,0.003208,0.015823,-0.110551,0.089495,0.059351,0.062480,...,-0.008380,-0.043360,-0.079457,-0.015142,0.057855,0.091263,0.027930,-0.014102,2014,12

In [18]:
train_firm_2018_temp

,ticker,gvkey,permno,sic,exchcd,shrcd,ffi49,year,ret,date,...,hs_20_11,hs_20_12,hs_20_13,hs_20_14,hs_20_15,hs_20_16,hs_20_17,hs_20_18,hs_20_19,month
0,ERTS,16721,75828,7372,3.0,11.0,36,1997,0.064718,1997-01-31,...,0.073095,0.012811,-0.021340,-0.091850,0.001624,0.083273,0.097302,0.020908,-0.004974,1
1,BMCS,14650,11976,7372,3.0,11.0,36,1997,0.048338,1997-01-31,...,0.079243,0.016592,-0.025942,-0.091290,0.005750,0.088067,0.102095,0.021969,-0.004713,1
2,LOW,6829,61399,5211,1.0,11.0,43,1997,-0.068632,1997-01-31,...,0.082286,0.012418,-0.018880,-0.087804,0.006796,0.087420,0.095943,0.014748,-0.007162,1
3,NKE,7906,57665,3021,1.0,11.0,10,1997,0.139583,1997-01-31,...,0.082985,0.020682,-0.033000,-0.086920,-0.008532,0.082152,0.096230,0.021234,0.003915,1
4,CPC,61404,82295,7500,1.0,11.0,33,1997,0.014925,1997-01-31,...,0.081996,0.032252,-0.025587,-0.091589,-0.000745,0.086854,0.092682,0.020225,0.002370,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200964,NOC,7985,24766,3812,1.0,11.0,37,2014,0.045838,2014-12-31,...,0.080041,0.013006,-0.021230,-0.088243,0.007252,0.078170,0.084771,0.015597,0.008715,12
200965,CVX,2991,14541,2911,1.0,11.0,30,2014,0.030403,2014-12-31,...,0.071782,0.004970,-0.032172,-0.095391,0.016860,0.078163,0.071052,0.015788,-0.005237,12
200966,NOV,63892,84032,3533,1.0,11.0,21,2014,-0.015662,2014-12-31,...,0.076181,0.016469,-0.031374,-0.094377,0.005681,0.077192,0.069058,0.012797,0.016623,12
200967,APO,184254,12591,6282,1.0,11.0,48,2014,-0.035188,2014-12-31,...,0.087045,0.027390,-0.029939,-0.107373,-0.012164,0.069386,0.071665,0.021660,0.016057,12
200968,ZTS,13721,13788,2834,1.0,11.0,13,2014,-0.042288,2014-12-31,...,0.078946,0.017741,-0.020436,-0.089969,-0.002365,0.079082,0.093672,0.021937,0.001318,12

## **데이터 저장**

In [19]:
## Save
output_file_path = os.path.join(base_path2, 'mergedData', '02_M5020_F5020')
os.makedirs(output_file_path, exist_ok=True)

train_2018.to_csv(os.path.join(output_file_path, 'train2018.csv'), index=False)
valid_2018.to_csv(os.path.join(output_file_path, 'valid2018.csv'), index=False)
test_2018.to_csv(os.path.join(output_file_path, 'test2018.csv'), index=False)

train_2019.to_csv(os.path.join(output_file_path, 'train2019.csv'), index=False)
valid_2019.to_csv(os.path.join(output_file_path, 'valid2019.csv'), index=False)
test_2019.to_csv(os.path.join(output_file_path, 'test2019.csv'), index=False)

train_2020.to_csv(os.path.join(output_file_path, 'train2020.csv'), index=False)
valid_2020.to_csv(os.path.join(output_file_path, 'valid2020.csv'), index=False)
test_2020.to_csv(os.path.join(output_file_path, 'test2020.csv'), index=False)

train_2021.to_csv(os.path.join(output_file_path, 'train2021.csv'), index=False)
valid_2021.to_csv(os.path.join(output_file_path, 'valid2021.csv'), index=False)
test_2021.to_csv(os.path.join(output_file_path, 'test2021.csv'), index=False)